Repository mumble-voip/mumble, pull requests merged in 2020-06, with the labels that each got.

#4231 src/mumble/OverlayText.h: add missing <QtGui/QPainterPath> include for Qt 5.15
  src/mumble/OverlayText.h
Labels: backport-needed, build, client, linux, qt

#4232 Backport "src/mumble/OverlayText.h: add missing <QtGui/QPainterPath> include for Qt 5.15"
  src/mumble/OverlayText.h
Labels: backport, build, client, linux, qt

#4229 src/mumble/NetworkConfig.cpp: Added missing include
  src/mumble/NetworkConfig.cpp
Labels: bug, build

#4235 Backport "Fix DB structure version not getting updated on table update"
  src/murmur/ServerDB.cpp
Labels: backport

#4234 Fix DB structure version not getting updated on table update
  src/murmur/ServerDB.cpp
Labels: bug

#4196 Add permission for Reset Comment/Avatar
  src/ACL.cpp
  src/ACL.h
  src/mumble/ACLEditor.cpp
  src/mumble/MainWindow.cpp
  src/mumble/mumble_en.ts
  src/murmur/Messages.cpp
  src/murmur/Murmur.ice
Labels: acl

#4209 Stereo stream decoding and playing support
  src/mumble/AudioOutput.cpp
  src/mumble/AudioOutput.h
  src/mumble/AudioOutputSample.cpp
  src/mumble/AudioOutputSample.h
  src/mumble/AudioOutputSpeech.cpp
  src/mumble/AudioOutputSpeech.h
  src/mumble/AudioOutputUser.cpp
  src/mumble/AudioOutputUser.h
  src/mumble/OpusCodec.cpp
  src/mumble/OpusCodec.h
Labels: audio, client

#4242 Fix "empty entry bug"
  src/mumble/TalkingUI.cpp
Labels: client, ui

#4240 Move positional audio option to proper section
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioConfigDialog.h
  src/mumble/AudioOutput.ui
  src/mumble/mumble_en.ts
Labels: client, ui

#4245 CXX-STANDARD: Enforce (at least) cpp14
  qmake/cplusplus.pri
Labels: build

#4243 Group all attenuation settings together
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioConfigDialog.h
  src/mumble/AudioOutput.ui
  src/mumble/mumble_en.ts
Labels: client, ui

#4105 Use REPLACE instead of INSERT
  src/murmur/ServerDB.cpp
Labels: bug, server

#4246 Backport "Use REPLACE instead of INSERT"
  src/murmur/ServerDB.cpp
Labels: backport

#4249 src/mumble/Markdown.cpp remove double html escaping from markdown.
  src/mumble/Markdown.cpp
Labels: bug, client

#4227 Safeguard from potential attacks against OCB2
  src/CryptState.cpp
  src/CryptState.h
  src/mumble/ServerHandler.cpp
  src/murmur/Server.cpp
  src/tests/TestCrypt/TestCrypt.cpp
Labels: backport-needed, bug

#4251 Backport "Safeguard from potential attacks against OCB2"
  src/CryptState.cpp
  src/CryptState.h
  src/mumble/ServerHandler.cpp
  src/murmur/Server.cpp
  src/tests/TestCrypt/TestCrypt.cpp
Labels: backport

#4253 TalkingUI: Fix ghost users
  src/mumble/Messages.cpp
  src/mumble/TalkingUI.cpp
  src/mumble/TalkingUI.h
Labels: bug, client, ui

#4254 src/CoreAudio: update CoreAudio API, remove deprecated API calls.
  src/mumble/CoreAudio.cpp
  src/mumble/CoreAudio.h
Labels: audio, code

#4256 src/mumble: remove positional audio check in audio backends
  src/mumble/ALSAAudio.cpp
  src/mumble/OSS.cpp
  src/mumble/PulseAudio.cpp
  src/mumble/PulseAudio.h
Labels: audio, client

#4264 src/Qt4Compat.h: add newline at end of file
  src/Qt4Compat.h
Labels: build

#4250 Fix: Resizing buffer in audio callback causes mumble to crash
  src/mumble/AudioOutput.cpp
  src/mumble/AudioOutput.h
  src/mumble/AudioOutputSample.cpp
  src/mumble/AudioOutputSample.h
  src/mumble/AudioOutputSpeech.cpp
  src/mumble/AudioOutputSpeech.h
  src/mumble/AudioOutputUser.cpp
  src/mumble/AudioOutputUser.h
  src/mumble/CoreAudio.cpp
  src/mumble/PulseAudio.cpp
  src/mumble/PulseAudio.h
Labels: audio, bug

#4267 src/mumble/AudioOutput.ui: Fix stacked elements
  src/mumble/AudioOutput.ui
Labels: bug, client, ui

#4280 CI: change update target for AppImages
  scripts/azure-pipelines/build_linux.bash
Labels: ci

#4276 Replace deprecated constructs
  src/ACL.cpp
  src/SSL.cpp
  src/mumble/ConnectDialog.cpp
  src/mumble/MainWindow.cpp
  src/mumble/XMLTools.cpp
  src/mumble/main.cpp
  src/murmur/Meta.cpp
  src/murmur/Register.cpp
  src/murmur/Server.cpp
  src/murmur/main.cpp
  src/tests/Benchmark.cpp
Labels: code

#4282 Fix overlay
  src/mumble/Overlay.cpp
  src/mumble/Overlay.h
Labels: bug, client, overlay

#4265 Send image pasted into the chat bar
  src/mumble/CustomElements.cpp
  src/mumble/CustomElements.h
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/mumble_en.ts
Labels: client, feature-request, ui

#4285 REFAC(lgtm): Removed subsequently overwritten key
  scripts/generate-cipherinfo.py
Labels: code

#4293 FIX(certificate): Properly process signed certificates
  src/SSL.cpp
Labels: bug

#4275 MAINT: Create commit guidelines
  COMMIT_GUIDELINES.md
Labels: documentation, github

#4287 Allow disabling of TTS for specific users
  src/mumble/ClientUser.cpp
  src/mumble/ClientUser.h
  src/mumble/Database.cpp
  src/mumble/Database.h
  src/mumble/Log.cpp
  src/mumble/Log.h
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/MainWindow.ui
  src/mumble/Messages.cpp
  src/mumble/mumble_en.ts
Labels: client, feature-request

#4244 UserLocalVolumeDialog: "Inherit" AlwaysOnTop behavior
  src/mumble/UserLocalVolumeDialog.cpp
Labels: bug, client, ui

#4307 FIX(text-chat): Fix crash on TextMessage from server
  src/mumble/Messages.cpp
Labels: bug, client

#4301 FEAT(client): Log a message if some change could not be saved due to missing certificate
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/UserLocalVolumeDialog.cpp
  src/mumble/mumble_en.ts
Labels: client, feature-request

#4312 FIX(tts): OmitScope/OmitAuthor no longer reads HTML-formatted message
  src/mumble/Messages.cpp
  src/mumble/mumble_en.ts
Labels: accessibility, bug, client

#4306 FIX(talking-ui): Fix glitch on session reuse
  src/mumble/TalkingUI.cpp
Labels: bug, client, ui

#4291 Revamp ServerBrowser UI
  src/mumble/ConnectDialog.cpp
  src/mumble/ConnectDialog.h
  src/mumble/ConnectDialog.ui
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/mumble_en.ts
Labels: client, feature-request, ui

#4326 FIX(talking-ui): Fix local user added multiple times
  src/mumble/TalkingUI.cpp
Labels: bug, client, ui

#4327 Fix typos in Mumble.proto
  src/Mumble.proto
Labels: code

#4330 FIX(typo): Fixed missing slash in closing <p>-tag
  src/mumble/NetworkConfig.cpp
  src/mumble/mumble_en.ts
Labels: translation
