Repository mumble-voip/mumble, pull requests merged in 2020-05, with the labels that each got.

#4113 Improve echo cancellation settings ui
  src/mumble/ASIOInput.cpp
  src/mumble/ASIOInput.h
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioConfigDialog.h
  src/mumble/AudioInput.ui
  src/mumble/ConfigDialog.cpp
  src/mumble/ConfigDialog.h
  src/mumble/ConfigWidget.h
  src/mumble/GlobalShortcut.cpp
  src/mumble/GlobalShortcut.h
  src/mumble/LCD.cpp
  src/mumble/LCD.h
  src/mumble/Log.cpp
  src/mumble/Log.h
  src/mumble/LookConfig.cpp
  src/mumble/LookConfig.h
  src/mumble/NetworkConfig.cpp
  src/mumble/NetworkConfig.h
  src/mumble/OverlayConfig.cpp
  src/mumble/OverlayConfig.h
  src/mumble/Plugins.cpp
  src/mumble/Plugins.h
Labels: client, ui

#4124 qmake/compiler.pri: remove "/Z7" flag from compiler options
  qmake/compiler.pri
Labels: build, needs-backport, windows

#4126 Backport "qmake/compiler.pri: remove "/Z7" flag from compiler options"
  qmake/compiler.pri
Labels: backport, build, windows

#4117 Fix ChannelListener not hearing shout if no real user is in shouted channel
  src/murmur/Messages.cpp
  src/murmur/Server.cpp
  src/murmur/Server.h
  src/murmur/ServerUser.h
Labels: bug, server

#4119 Added DBus methods for setting/querying the current transmit mode
  src/mumble/DBus.cpp
  src/mumble/DBus.h
  src/mumble/MainWindow.h
Labels: client

#4118 Added setting for TalkingUI to keep local user visible
  src/mumble/LookConfig.cpp
  src/mumble/LookConfig.ui
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/Messages.cpp
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/TalkingUI.cpp
  src/mumble/TalkingUI.h
  src/mumble/main.cpp
  src/mumble/mumble_en.ts
Labels: client, enhancement, ui

#4152 Fixed UserIndex::rowOf() function for listener proxies
  src/mumble/UserModel.cpp
  src/mumble/UserModel.h
Labels: bug, client, ui

#4156 Added check for unprocessed translations
  .azure-pipelines.yml
  scripts/azure-pipelines/assertNoTranslationChanges.sh
  scripts/azure-pipelines/install-environment_linux_translations.bash
  src/mumble/mumble_en.ts
Labels: ci, translation

#4149 Join user's channel context action
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/MainWindow.ui
  src/mumble/mumble_en.ts
Labels: client, ui

#4158 Documention on ContextActionModify
  src/Mumble.proto
Labels: code, documentation

#4144 Implemented options to display channel hierarchy in TalkingUI
  src/mumble/ConfigDialog.cpp
  src/mumble/ConfigDialog.h
  src/mumble/LookConfig.cpp
  src/mumble/LookConfig.h
  src/mumble/LookConfig.ui
  src/mumble/MainWindow.cpp
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/TalkingUI.cpp
  src/mumble/TalkingUI.h
Labels: client, ui

#4166 Backport "fix sqlite version requirement"
  src/murmur/ServerDB.cpp
Labels: backport

#4168 Made font size for TalkingUI entries configurable
  src/mumble/LookConfig.cpp
  src/mumble/LookConfig.ui
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/TalkingUI.cpp
  src/mumble/TalkingUI.h
  src/mumble/mumble_en.ts
Labels: client, ui

#4138 Don't hide the setting if no-update config was used
  src/mumble/MainWindow.cpp
  src/mumble/NetworkConfig.cpp
  src/mumble/Settings.cpp
Labels: client, code

#4174 Added tooltip for echo cancellation
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioInput.ui
  src/mumble/mumble_en.ts
Labels: client, documentation, ui

#4155 Added option to add custom window title extension
  src/mumble/Global.h
  src/mumble/MainWindow.cpp
  src/mumble/main.cpp
  src/mumble/mumble_en.ts
Labels: client

#4148 Allow user-context menu to be triggered from the TalkingUI
  src/mumble/TalkingUI.cpp
Labels: client, ui

#4123 Fix iInFlightTCPPings check
  src/mumble/ServerHandler.cpp
  src/mumble/Settings.cpp
Labels: client, needs-backport

#4192 Backport "Fix iInFlightTCPPings check"
  src/mumble/ServerHandler.cpp
  src/mumble/Settings.cpp
Labels: backport

#4185 TalkingUI: Fix race leading to crash
  src/mumble/TalkingUI.cpp
Labels: bug, client

#4165 Remove overlay related code if no-overlay option is used
  src/mumble/ConfigDialog.cpp
  src/mumble/Global.cpp
  src/mumble/Global.h
  src/mumble/GlobalShortcut_win.cpp
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/Messages.cpp
  src/mumble/UserModel.cpp
  src/mumble/main.cpp
  src/mumble/mumble.pro
Labels: code

#4198 Backport "Document settings missing in example murmur.ini"
  scripts/murmur.ini
Labels: backport

#4200 3rdparty/jack-src: add systemdeps.h
  3rdparty/jack-src/jack/systemdeps.h
Labels: build

#4202 src/Mumble/JackAudio.cpp: remove C++17 usage in JackAudioOutput::run()
  src/mumble/JackAudio.cpp
Labels: build, client

#4182 Show warning message for enabling update checks with no-update config
  src/mumble/NetworkConfig.cpp
  src/mumble/NetworkConfig.h
  src/mumble/mumble_en.ts
Labels: client, enhancement, ui

#4204 Add mumble icon file
  installer/Files.wxs
Labels: client, installer, needs-backport, windows

#4172 Positional Audio: Do not assume Y up for small errors
  src/mumble/AudioOutput.cpp
Labels: client, positional audio

#4205 Backport "Add mumble icon file"
  installer/Files.wxs
Labels: backport

#4167 Fix echo cancellation bug + add command line option to dump AudioInput streams
  docs/AudioInputDebug.md
  docs/AudioInputDebugFiles/bug.png
  docs/AudioInputDebugFiles/fix.png
  docs/AudioInputDebugFiles/fsm.png
  src/mumble/AudioInput.cpp
  src/mumble/AudioInput.h
  src/mumble/Global.cpp
  src/mumble/Global.h
  src/mumble/main.cpp
  src/mumble/mumble_en.ts
Labels: audio, client, needs-backport

#3896 Disable winhooks if screen reader is active
  src/mumble/GlobalShortcut_win.cpp
  src/mumble/GlobalShortcut_win.h
Labels: GlobalShortcuts, accessibility, client, needs-testing

#4215 Set the echo combo box to "off" before disabling it
  src/mumble/AudioConfigDialog.cpp
Labels: client, enhancement, ui

#4214 Enable echo cancellation by default
  src/mumble/Settings.cpp
Labels: audio, client

#4217 Fixed infinite loop caused by #4215
  src/mumble/AudioConfigDialog.cpp
Labels: bug, client, ui

#4220 Fix database encoding
  src/murmur/ServerDB.cpp
  src/murmur/ServerDB.h
Labels: bug, server

#4222 Backport "Fix database encoding"
  src/murmur/ServerDB.cpp
  src/murmur/ServerDB.h
Labels: backport

#4211 More accessibility enhancements for accessibility clients
  src/mumble/ACLEditor.cpp
  src/mumble/ASIOInput.cpp
  src/mumble/About.cpp
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioStats.cpp
  src/mumble/AudioWizard.cpp
  src/mumble/BanEditor.cpp
  src/mumble/Cert.cpp
  src/mumble/ConfigDialog.cpp
  src/mumble/ConnectDialog.cpp
  src/mumble/GlobalShortcut.cpp
  src/mumble/LCD.cpp
  src/mumble/Log.cpp
  src/mumble/LookConfig.cpp
  src/mumble/MainWindow.cpp
  src/mumble/NetworkConfig.cpp
  src/mumble/OverlayEditor.cpp
  src/mumble/Plugins.cpp
  src/mumble/TextMessage.cpp
  src/mumble/Tokens.cpp
  src/mumble/UserEdit.cpp
  src/mumble/UserLocalVolumeDialog.cpp
  src/mumble/VoiceRecorderDialog.cpp
  src/mumble/mumble_en.ts
Labels: accessibility, client, ui
