Repository mumble-voip/mumble, pull requests merged in 2020-12, with the labels that each got.

#4597 MAINT: Fix PR template not working
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: github

#4617 FIX(client): Crash due to race-condition in TalkingUI
  src/mumble/TalkingUI.cpp
  src/mumble/TalkingUI.h
Labels: bug, client, ui

#4616 FIX(server): Prevent listeners from hearing all shouts
  src/murmur/Server.cpp
Labels: bug, server

#4611 FIX(client): Respect unlimited imagemessagelength
  src/mumble/CustomElements.cpp
Labels: backport-needed, bug, client

#4619 MAINT/FIX(server): Fix systemd murmur.service
  scripts/murmur.service
Labels: linux, server

#4629 BUILD(cmake): Fix overlay link option being overwritten
  overlay_gl/CMakeLists.txt
Labels: build

#4574 REFAC(installer-msi) Simplify WiX component install
  .ci/azure-pipelines/build_windows.bat
  .ci/azure-pipelines/install-environment_windows.ps1
  .ci/azure-pipelines/steps_windows.yml
  CMakeLists.txt
  cmake/packaging.cmake
  installer/ClientInstaller.cs
  installer/Files.wxs
  installer/Mumble.rtf
  installer/MumbleInstall.cs
  installer/MumbleInstall.sln
  installer/MumbleInstall.wixproj
  installer/MumbleUCRTComponentRefs.wxi
  installer/MumbleUCRTComponents.wxi
  installer/MurmurUCRTComponentRefs.wxi
  installer/MurmurUCRTComponents.wxi
  installer/Plugins.wxs
  installer/Product.wxs
  installer/ServerInstaller.cs
  installer/Settings.wxi
  installer/Translations/Czech.wxl
  installer/Translations/Danish.wxl
  installer/Translations/Dutch.wxl
  installer/Translations/English.wxl
  installer/Translations/Finnish.wxl
  installer/Translations/French.wxl
  installer/Translations/German.wxl
  installer/Translations/Greek.wxl
  installer/Translations/Italian.wxl
  installer/Translations/Japanese.wxl
  installer/Translations/Norwegian.wxl
  installer/Translations/Polish.wxl
  installer/Translations/Portuguese.wxl
  installer/Translations/Russian.wxl
  installer/Translations/SimpChinese.wxl
  installer/Translations/Spanish.wxl
  installer/Translations/Swedish.wxl
  installer/Translations/TradChinese.wxl
  installer/Translations/Turkish.wxl
  installer/UI.wxs
  installer/build_installer.pl
  installer/client-shortcuts.xml
  installer/gen-ucrt.py
  installer/server-shortcuts.xml
  installer/wix-template.xml
  plugins/CMakeLists.txt
  scripts/Create-Win32InstallerMUI.ps1
  src/mumble_exe/CMakeLists.txt
  src/murmur/CMakeLists.txt
Labels: installer

#4637 FIX(installer) Remove ini file
  installer/ServerInstaller.cs
Labels: installer, server

#4635 FIX(client, talking-ui): Icon size initialized incorrectly
  src/mumble/TalkingUI.cpp
Labels: bug, client, ui

#4633 FIX: Revert audio corking (PulseAudio)
  src/mumble/AudioWizard.cpp
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/PulseAudio.cpp
  src/mumble/PulseAudio.h
  src/mumble/main.cpp
Labels: audio, bug, client

#4640 BUILD(cmake): Fix overlay link option being overwritten 2.0
  overlay_gl/CMakeLists.txt
Labels: build

#4634 REFAC(client, talking-ui): Stylable widget wrapper
  src/mumble/CMakeLists.txt
  src/mumble/TalkingUI.cpp
  src/mumble/TalkingUI.h
  src/mumble/TalkingUIComponent.h
  src/mumble/TalkingUIContainer.cpp
  src/mumble/TalkingUIContainer.h
  src/mumble/TalkingUIEntry.cpp
  src/mumble/TalkingUIEntry.h
  src/mumble/widgets/MultiStyleWidgetWrapper.cpp
  src/mumble/widgets/MultiStyleWidgetWrapper.h
Labels: client, code, ui

#4632 FEAT(client): Easier pasting of images
  src/mumble/CustomElements.cpp
  src/mumble/CustomElements.h
  src/mumble/Log.cpp
  src/mumble/Log.h
  src/mumble/mumble_en.ts
Labels: feature-request

#4644 FIX(client, server): Load native mDNS/DNS-SD symbols at runtime
  src/mumble/Zeroconf.cpp
  src/mumble/Zeroconf.h
  src/murmur/Zeroconf.cpp
  src/murmur/Zeroconf.h
Labels: client, server

#4649 BUILD(macOS): Only include ".dylib" files in bundle's "Plugins" directory
  macx/scripts/osxdist.py
Labels: build, macOS

#4650 TRANSLATION: Remove duplicate empty ts files
  src/mumble/mumble_ca_ES.ts
  src/mumble/mumble_el_GR.ts
  src/mumble/mumble_nb_NO.ts
Labels: translation

#4651 MAINT: Fix typo in commit guidelines
  COMMIT_GUIDELINES.md
Labels: documentation

#4652 MAINT: Add TRANSLATION type to commit guidelines
  COMMIT_GUIDELINES.md
Labels: documentation
