Repository mumble-voip/mumble, pull requests merged in 2020-04, with the labels that each got.

#4029 Set non-empty path correctly
  src/mumble/DBus.cpp
Labels: bug, mumble

#4030 src/mumble/ClientUser.cpp: Narrow down the scope of QWriteLocker
  src/mumble/ClientUser.cpp
Labels: code, mumble

#4032 src/murmur/Server.cpp: implement workaround for critical QSslSocket issue
  src/murmur/Server.cpp
Labels: murmur, needs-backport, qt

#4034 Readme improvements
  README.md
  screenshots/Mumble.png
Labels: documentation

#4033 Document settings missing in example murmur.ini
  scripts/murmur.ini
Labels: documentation

#3476 murmur_grpc: check if an environment variable is set and don't use "which" on Windows
  src/murmur/murmur_grpc/murmur_grpc.pro
Labels: build, murmur

#4040 src/murmur/murmur_grpc/murmur_grpc.pro: Fix GRPC build
  src/murmur/murmur_grpc/murmur_grpc.pro
Labels: build, mumble

#4038 src: Fix for b263b91
  src/HostAddress.cpp
  src/OSInfo.cpp
  src/mumble/AudioStats.cpp
Labels: code

#4041 Fix overlay start
  src/mumble/Overlay.cpp
  src/mumble/Overlay.h
  src/mumble/Overlay_macx.mm
  src/mumble/Overlay_unix.cpp
  src/mumble/Overlay_win.cpp
  src/mumble/Settings.cpp
  src/mumble/main.cpp
Labels: mumble, overlay

#4026 Improve log message style
  src/mumble/Log.cpp
  src/mumble/Log.ui
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/mumble_en.ts
Labels: mumble, ui

#4037 1.3.1
  .cirrus.yml
  .lgtm.yml
  g15helper/g15helper.plist
  g15helper/g15helper.rc
  installer/Settings.wxi
  macx/common.pri
  macx/osax/osax.plist
  overlay/mumble_ol.rc
  overlay/overlay-shared.pro
  overlay/overlay_exe/overlay_exe.rc
  overlay_gl/overlay_gl.pro
  overlay_winx64/mumble_ol.rc
  overlay_winx64/overlay_exe_winx64/overlay_exe.rc
  plugins/mumble_plugin.h
  scripts/azure-pipelines/build_macos.bash
  scripts/azure-pipelines/install-environment.ps1
  scripts/travis-ci/before_install.bash
  scripts/travis-ci/script.bash
  src/SSL.cpp
  src/mumble.pri
  src/mumble/AudioOutput.ui
  src/mumble/ConnectDialog.cpp
  src/mumble/DBus.cpp
  src/mumble/MainWindow.cpp
  src/mumble/ManualPlugin.cpp
  src/mumble/ManualPlugin.ui
  src/mumble/Messages.cpp
  src/mumble/Overlay.cpp
  src/mumble/Overlay.h
  src/mumble/Overlay_macx.mm
  src/mumble/Overlay_unix.cpp
  src/mumble/Overlay_win.cpp
  src/mumble/PulseAudio.cpp
  src/mumble/ServerHandler.cpp
  src/mumble/ServerHandler.h
  src/mumble/Settings.cpp
  src/mumble/UserLocalVolumeDialog.ui
  src/mumble/UserModel.cpp
  src/mumble/UserModel.h
  src/mumble/WebFetch.cpp
  src/mumble/main.cpp
  src/mumble/mumble.plist
  src/mumble/mumble.rc
  src/mumble/mumble_dll.rc
  src/mumble/mumble_en.ts
  src/murmur/Messages.cpp
  src/murmur/Server.cpp
  src/murmur/ServerUser.cpp
  src/murmur/ServerUser.h
  src/murmur/murmur.plist
  src/murmur/murmur.rc
Labels: release-management

#4051 Fix racecondition for g.iTarget
  src/mumble/AudioInput.cpp
  src/mumble/AudioInput.h
Labels: audio, bug, client

#4050 Fix last audio frame target
  src/mumble/AudioInput.cpp
  src/mumble/Global.h
Labels: audio, bug, client

#4053 Moved concurrent dependency to other Qt deps
  src/mumble/mumble.pro
Labels: code

#4052 Backport some more fixes
  src/mumble/AudioInput.cpp
  src/mumble/AudioInput.h
  src/mumble/Global.h
Labels: backport

#4054 Use TCP_NODELAY by default and remove attempts to flush.
  src/Connection.cpp
Labels: code, enhancement

#4058 Add alias for places/network-workgroup.svg
  themes/ClassicTheme.qrc
  themes/MumbleTheme.qrc
Labels: bug, client, ui

#4048 Whisper to selection
  src/mumble/GlobalShortcut.cpp
  src/mumble/GlobalShortcut.h
  src/mumble/GlobalShortcutTarget.ui
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/Messages.cpp
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/UserModel.cpp
  src/mumble/UserModel.h
  src/mumble/mumble_en.ts
Labels: GlobalShortcuts, client

#4056 qmake: fix paths in toolchains to support recent Windows SDK versions
  qmake/toolchain/win32-msvc2015/x64.toolchain
  qmake/toolchain/win32-msvc2015/x86-xp.toolchain
  qmake/toolchain/win32-msvc2015/x86.toolchain
Labels: build, needs-backport, windows

#4061 Backport "Add alias for places/network-workgroup.svg"
  themes/ClassicTheme.qrc
  themes/MumbleTheme.qrc
Labels: backport, bug, client, ui

#4060 Backport "qmake: fix paths in toolchains to support recent Windows SDK versions"
  qmake/toolchain/win32-msvc2015/x64.toolchain
  qmake/toolchain/win32-msvc2015/x86-xp.toolchain
  qmake/toolchain/win32-msvc2015/x86.toolchain
Labels: backport, build, windows

#4059 Update GTA V Plugin
  plugins/gtav/gtav.cpp
Labels: client, positional audio

#4068 Backport 58d27c6
  3rdparty/qqbonjour-src/BonjourServiceBrowser.cpp
  3rdparty/qqbonjour-src/BonjourServiceResolver.cpp
  src/ACL.cpp
  src/Ban.cpp
  src/Channel.cpp
  src/Connection.cpp
  src/CryptState.cpp
  src/CryptographicHash.cpp
  src/CryptographicRandom.cpp
  src/FFDHE.cpp
  src/Group.cpp
  src/HTMLFilter.cpp
  src/HostAddress.cpp
  src/License.cpp
  src/LogEmitter.cpp
  src/Net.cpp
  src/OSInfo.cpp
  src/PasswordGenerator.cpp
  src/PlatformCheck.cpp
  src/SSL.cpp
  src/SSLCipherInfo.cpp
  src/SSLLocks.cpp
  src/SelfSignedCertificate.cpp
  src/ServerAddress.cpp
  src/ServerResolver_nosrv.cpp
  src/ServerResolver_qt5.cpp
  src/Timer.cpp
  src/UnresolvedServerAddress.cpp
  src/User.cpp
  src/Utils.h
  src/Version.cpp
  src/mumble/mumble_pch.hpp
  src/mumble/murmur_pch.h
  src/murmur/murmur_pch.h
Labels: backport

#4082 Fix grpc build
  scripts/travis-ci/before_install.bash
  scripts/travis-ci/script.bash
  src/murmur/MurmurGRPCImpl.cpp
  src/murmur/MurmurGRPCImpl.h
Labels: build, ci, code

#4076 Markdown support
  src/mumble/MainWindow.cpp
  src/mumble/Markdown.cpp
  src/mumble/Markdown.h
  src/mumble/TextMessage.cpp
  src/mumble/TextMessage.h
  src/mumble/mumble.pro
Labels: client, feature-request

#4097 Warn older clients about ChannelListeners
  src/murmur/Messages.cpp
Labels: enhancement, server

#4095 Optional start menu shortcut for installer
  installer/Files.wxs
  installer/Product.wxs
  installer/Settings.wxi
  installer/Translations/Czech.wxl
  installer/Translations/Danish.wxl
  installer/Translations/Dutch.wxl
  installer/Translations/English.wxl
  installer/Translations/Finnish.wxl
  installer/Translations/French.wxl
  installer/Translations/German.wxl
  installer/Translations/Greek.wxl
  installer/Translations/Italian.wxl
  installer/Translations/Japanese.wxl
  installer/Translations/Norwegian.wxl
  installer/Translations/Polish.wxl
  installer/Translations/Portuguese.wxl
  installer/Translations/Russian.wxl
  installer/Translations/SimpChinese.wxl
  installer/Translations/Spanish.wxl
  installer/Translations/Swedish.wxl
  installer/Translations/TradChinese.wxl
  installer/Translations/Turkish.wxl
Labels: enhancement, installer

#4099 free "path" only after we're done with "filename"
  plugins/mumble_plugin_linux.h
Labels: client

#4100 Revamp audio wizard
  src/mumble/AudioWizard.cpp
  src/mumble/AudioWizard.ui
  src/mumble/mumble_en.ts
Labels: client, enhancement, ui

#4101 Restrict string sizes for Version information
  src/murmur/Messages.cpp
Labels: bug, server

#4104 Fix qtconcurrent include path
  src/mumble/VersionCheck.cpp
Labels: build, client

#4114 Backport "Restrict string sizes for Version information"
  src/murmur/Messages.cpp
Labels: backport

#4066 Talking UI
  src/mumble/AudioOutputSpeech.cpp
  src/mumble/Global.cpp
  src/mumble/Global.h
  src/mumble/LookConfig.cpp
  src/mumble/LookConfig.ui
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/MainWindow.ui
  src/mumble/Messages.cpp
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/TalkingUI.cpp
  src/mumble/TalkingUI.h
  src/mumble/UserModel.cpp
  src/mumble/UserModel.h
  src/mumble/main.cpp
  src/mumble/mumble.pro
  src/mumble/mumble_en.ts
Labels: client, feature-request
