Repository mumble-voip/mumble, pull requests merged in 2020-10, with the labels that each got.

#4482 BUILD(cmake): Enable -Werr by default
  CMakeLists.txt
  cmake/compiler.cmake
  overlay/CMakeLists.txt
  src/CMakeLists.txt
  src/mumble/Log.cpp
  src/mumble/ServerHandler.cpp
  src/mumble/Settings.cpp
  src/mumble/TalkingUIEntry.cpp
  src/murmur/CMakeLists.txt
  src/murmur/MurmurIce.h
Labels: build

#4511 REFAC(client): move common stuff from getExportedSymbol() to a template function
  plugins/mumble_plugin_linux.h
Labels: client, code, positional audio

#4517 BUILD(docker): Updated Dockerfile to use CMake
  Dockerfile
Labels: build

#4524 FIX(client): don't print Zeroconf warning if the operation was cancelled
  src/mumble/Zeroconf.cpp
Labels: client

#4531 FEAT(ui): Add ability to paste and send messages using a keyboard shortcut
  src/mumble/CustomElements.cpp
Labels: client, ui

#4533 BUILD(cmake): Fix use of generator expression
  cmake/compiler.cmake
  g15helper/CMakeLists.txt
Labels: build

#4534 Overlay: improve find_odlsym(), add support for DT_GNU_HASH
  overlay_gl/init_unix.c
Labels: client, linux, overlay

#4510 FIX(cmake): Revise if condition for Release build type
  CMakeLists.txt
Labels: build

#4537 BUILD(cmake): Fix use of generator expression (follow-up)
  cmake/compiler.cmake
Labels: build

#4540 FEAT(server): Send text messages also to users only listening to channels
  src/murmur/Messages.cpp
Labels: feature-request, server

#4542 FIX(client): don't print Zeroconf warning if the operation was cancelled
  src/mumble/Zeroconf.cpp
Labels: client, windows

#4509 BUILD(cmake): Fix gRPC not being found
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/build_windows.bat
  .ci/azure-pipelines/install-environment_linux.bash
  .ci/travis-ci/before_install.bash
  .ci/travis-ci/script.bash
  .cirrus.yml
  cmake/compiler.cmake
  src/murmur/CMakeLists.txt
  src/murmur/MurmurGRPCImpl.h
Labels: bug, build

#4503 WIP: BUILD(cmake): Revamp install paths
  CMakeLists.txt
  cmake/install-paths.cmake
  cmake/packaging.cmake
  g15helper/CMakeLists.txt
  overlay/CMakeLists.txt
  overlay/overlay_exe/CMakeLists.txt
  overlay_gl/CMakeLists.txt
  plugins/CMakeLists.txt
  src/mumble/CELTCodec.cpp
  src/mumble/CMakeLists.txt
  src/mumble/OpusCodec.cpp
  src/mumble/Plugins.cpp
  src/mumble_exe/CMakeLists.txt
  src/murmur/CMakeLists.txt
Labels: build, code

#4546 FEAT(client, ui): Add button to reset all settings
  src/mumble/ConfigDialog.cpp
  src/mumble/ConfigDialog.ui
  src/mumble/mumble_en.ts
Labels: client, feature-request, ui

#4554 BUILD(cmake): Prefer absolute install paths
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/build_windows.bat
  .ci/travis-ci/script.bash
  cmake/install-paths.cmake
  src/mumble/CMakeLists.txt
Labels: bug, build, release-management

#4536 FEAT/REFAC(plugins): Add classes for process-related functions
  plugins/CMakeLists.txt
  plugins/HostLinux.cpp
  plugins/HostLinux.h
  plugins/HostWindows.cpp
  plugins/HostWindows.h
  plugins/Process.cpp
  plugins/Process.h
  plugins/ProcessLinux.cpp
  plugins/ProcessLinux.h
  plugins/ProcessWindows.cpp
  plugins/ProcessWindows.h
  plugins/mumble_plugin_linux.h
  plugins/mumble_plugin_utils.h
  plugins/se/CMakeLists.txt
  plugins/se/client.h
  plugins/se/common.h
  plugins/se/engine.h
  plugins/se/se.cpp
Labels: code, linux, positional audio, windows

#4555 MAINT(docker): Add ca-certificates package
  Dockerfile
Labels: release-management

#4560 BUILD: Support working directories other than repository root
  scripts/vcpkg/get_mumble_dependencies.ps1
Labels: build

#4556 BUILD(cmake): Only install shared libraries
  cmake/install-library.cmake
  src/mumble/CMakeLists.txt
Labels: build

#4561 FIX(client): Also respect MUMBLE_PLUGIN_PATH in debug mode
  src/mumble/Plugins.cpp
Labels: client
