Repository mumble-voip/mumble, pull requests merged in 2020-07, with the labels that each got.

#4333 FIX(talking-ui): Make TalkingUI float wit tiling WMs
  src/mumble/TalkingUI.cpp
Labels: bug, client, ui

#4336 REFAC(various): replace NULL with nullptr
  g15helper/g15helper_emu.cpp
  src/Channel.cpp
  src/Channel.h
  src/Connection.cpp
  src/EnvUtils.cpp
  src/Group.cpp
  src/LogEmitter.h
  src/OSInfo.cpp
  src/PlatformCheck.cpp
  src/SSL.cpp
  src/SSLCipherInfo.cpp
  src/SSLLocks.cpp
  src/SelfSignedCertificate.cpp
  src/ServerResolver.h
  src/Timer.cpp
  src/crypto/CryptographicHash.cpp
  src/mumble_exe/mumble_exe.cpp
  src/murmur/BonjourServer.cpp
  src/murmur/Cert.cpp
  src/murmur/DBus.cpp
  src/murmur/Messages.cpp
  src/murmur/Meta.cpp
  src/murmur/Meta.h
  src/murmur/MurmurGRPCImpl.cpp
  src/murmur/MurmurIce.cpp
  src/murmur/PBKDF2.cpp
  src/murmur/Server.cpp
  src/murmur/Server.h
  src/murmur/ServerDB.cpp
  src/murmur/ServerUser.cpp
  src/murmur/Tray.cpp
  src/murmur/UnixMurmur.cpp
  src/murmur/main.cpp
  src/tests/Emit.cpp
  src/tests/Lock.cpp
  src/tests/OverlayTest.cpp
  src/tests/Resample.cpp
  src/tests/TestCrypt/TestCrypt.cpp
  src/tests/TestLink.cpp
Labels: code

#4340 MAINT(snapshot-versions): Change snapshot version format
  scripts/mumble-version.py
Labels: release-management

#4339 FEAT(talking-ui): Show selected status icons in TalkingUI
  src/mumble/Messages.cpp
  src/mumble/TalkingUI.cpp
  src/mumble/TalkingUI.h
Labels: client, feature-request, ui

#4347 Backport "Fix overlay"
  scripts/travis-ci/before_install.bash
  src/mumble/Overlay.cpp
  src/mumble/Overlay.h
Labels: backport

#4349 CI(azure): Fix brew-error for installed packages
  scripts/azure-pipelines/install-environment_macos.bash
Labels: ci

#4348 Backport: FIX(cert, mac): Avoid adding key pairs into system's keychain of MacOS.
  src/murmur/Server.cpp
Labels: backport

#4345 FIX(cert, mac): Avoid adding key pairs into system's keychain of MacOS.
  src/murmur/Server.cpp
Labels: bug, macOS, server

#4147 FEAT(server): Add rememberduration option
  scripts/murmur.ini
  src/murmur/Messages.cpp
  src/murmur/Meta.cpp
  src/murmur/Meta.h
  src/murmur/Server.cpp
  src/murmur/Server.h
  src/murmur/ServerDB.cpp
  src/murmur/ServerDB.h
  src/murmur/main.cpp
  src/murmur/murmur.pro
Labels: server

#4316 Allow disabling the public-server-list
  src/mumble/ConnectDialog.cpp
  src/mumble/NetworkConfig.cpp
  src/mumble/NetworkConfig.ui
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/mumble_en.ts
Labels: client, feature-request

#4342 MAINT(readme): Rework READMEs
  README
  README.Linux
  README.md
  docs/additional-readmes/README.static.linux
  docs/additional-readmes/README.static.osx
  installer/Files.wxs
  macx/scripts/osxdist.py
Labels: github

#4360 FIX(translation): Make "Ignore"-string translatable
  src/mumble/ConnectDialogEdit.ui
  src/mumble/mumble_en.ts
Labels: bug, translation

#4352 FEAT(manual-plugin): Show speaker's position
  src/mumble/AudioOutput.cpp
  src/mumble/AudioOutput.h
  src/mumble/ManualPlugin.cpp
  src/mumble/ManualPlugin.h
  src/mumble/ManualPlugin.ui
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/mumble_en.ts
Labels: client, feature-request, ui

#4358 FIX(shortcuts-ui): Clear selection after remove
  src/mumble/GlobalShortcut.cpp
Labels: bug, ui

#4344 FEAT(server): Allow loading welcome text from file
  scripts/murmur.ini
  src/murmur/Meta.cpp
  src/murmur/Meta.h
  src/murmur/Server.cpp
  src/murmur/Server.h
Labels: feature-request, server

#4361 FIX(client): Always run Disconnected-EH on exit
  src/mumble/MainWindow.cpp
  src/mumble/main.cpp
Labels: bug, client

#4371 CI(azure-pipelines): use correct path for build output
  .azure-pipelines.yml
  scripts/azure-pipelines/build_linux.bash
  scripts/azure-pipelines/build_macos.bash
  scripts/azure-pipelines/build_windows.bat
Labels: ci

#4372 REFAC(ci): move scripts to dedicated ".ci" folder, templatize Azure Pipelines steps
  .azure-pipelines.yml
  .ci/azure-pipelines/assertNoTranslationChanges.sh
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/build_windows.bat
  .ci/azure-pipelines/install-environment_linux.bash
  .ci/azure-pipelines/install-environment_linux_translations.bash
  .ci/azure-pipelines/install-environment_macos.bash
  .ci/azure-pipelines/install-environment_windows.ps1
  .ci/azure-pipelines/steps_linux.yml
  .ci/azure-pipelines/steps_macos.yml
  .ci/azure-pipelines/steps_windows.yml
  .ci/azure-pipelines/task-environment-cache.yml
  .ci/azure-pipelines/task-publish-artifacts.yml
  .ci/travis-ci/before_install.bash
  .ci/travis-ci/script.bash
  .travis.yml
Labels: ci

#4374 CI(azure-pipelines): add configuration for non-PR builds, store files in ".ci"
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
Labels: ci

#4375 CI(azure-pipelines): fix template paths
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
Labels: ci

#4379 FIX(overlay): only use minhook for 64 bit overlay library, add missing <unknwn.h>
  overlay/CMakeLists.txt
  overlay/HardHook_x86.h
Labels: build, overlay, windows

#4368 CI(azure-pipelines): use our own macOS builder for releases
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
  .ci/azure-pipelines/steps_macos.yml
Labels: ci

#4383 FEAT(talking-ui): Make channels selectable
  src/mumble/CMakeLists.txt
  src/mumble/TalkingUI.cpp
  src/mumble/TalkingUI.h
  src/mumble/TalkingUISelection.cpp
  src/mumble/TalkingUISelection.h
  src/mumble/mumble.pro
Labels: client, feature-request, ui
