Repository mumble-voip/mumble, pull requests merged in 2020-11, with the labels that each got.

#4564 DOCS: Added instructions to install Visual Studio
  docs/dev/build-instructions/README.md
  docs/dev/build-instructions/build_static.md
  docs/dev/build-instructions/build_windows.md
  docs/dev/build-instructions/setup_visual_studio.md
Labels: documentation

#4566 REFAC(plugins): Use Toolhelp32ReadProcessMemory() instead of ReadProcessMemory(), move "m_ok" to Process
  plugins/HostLinux.cpp
  plugins/HostLinux.h
  plugins/HostWindows.cpp
  plugins/HostWindows.h
  plugins/Process.cpp
  plugins/Process.h
  plugins/ProcessLinux.cpp
  plugins/ProcessWindows.cpp
Labels: client, windows

#4543 FEAT(client): Show keys in tooltip in shortcuts settings, each one in a new line
  src/mumble/GlobalShortcut.cpp
  src/mumble/GlobalShortcut.h
  src/mumble/mumble_en.ts
Labels: GlobalShortcuts, client, ui

#4565 FIX(positional-audio): Wrong character size used for wide strings
  plugins/mumble_plugin_utils.h
  plugins/ut99/ut99.cpp
Labels: client

#4568 REFAC(positional-audio): Proper functions/classes for module-related operations
  plugins/HostLinux.cpp
  plugins/HostLinux.h
  plugins/HostWindows.cpp
  plugins/HostWindows.h
  plugins/Module.cpp
  plugins/Module.h
  plugins/Process.h
  plugins/ProcessLinux.cpp
  plugins/ProcessWindows.cpp
  plugins/mumble_plugin_utils.h
  plugins/se/CMakeLists.txt
  plugins/se/se.cpp
Labels: client, positional audio

#4572 FIX(positional-audio): Fix Source Engine plugin using wrong player ID on Linux
  plugins/se/client.h
Labels: client, positional audio

#4571 FEAT(positional-audio): Add plugin for Among Us
  plugins/Process.cpp
  plugins/Process.h
  plugins/amongus/CMakeLists.txt
  plugins/amongus/Game.cpp
  plugins/amongus/Game.h
  plugins/amongus/amongus.cpp
  plugins/amongus/structs.h
  plugins/mumble_plugin_utils.h
Labels: client, positional audio

#4582 FIX(talking-ui): Context-menu z-index issues
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/TalkingUI.cpp
Labels: bug, client

#4586 DOCS: Note about selecting OpenSSL directory
  docs/dev/build-instructions/build_macos.md
  docs/dev/build-instructions/faq.md
Labels: documentation

#4587 DOCS: Overlay xcompile dependency
  docs/dev/build-instructions/build_linux.md
Labels: documentation

#4590 MAINT: Create PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: github

#4596 Add g++-multilib to Linux build docs
  docs/dev/build-instructions/build_linux.md
Labels: documentation

#4599 DOCS: Add link to cmake download page
  docs/dev/build-instructions/build_linux.md
Labels: documentation

#4605 CI: Introduce GitHub Actions
  .github/actions/install-dependencies/action.yml
  .github/actions/install-dependencies/extractWithProgress.sh
  .github/actions/install-dependencies/install_ubuntu_shared_64bit.sh
  .github/actions/install-dependencies/install_ubuntu_static_64bit.sh
  .github/actions/install-dependencies/main.sh
  .github/workflows/build.yml
  .github/workflows/set_environment_variables.sh
Labels: ci
