Repository mumble-voip/mumble, pull requests merged in 2020-08, with the labels that each got.

#4390 CI(windows): Potential download speedup
  .ci/azure-pipelines/install-environment_windows.ps1
Labels: ci

#4388 FIX(ui): Make chatwidget max height >= than its minimum height
  src/mumble/CustomElements.cpp
Labels: bug, client, ui

#4370 FIX(server): Reorder old table drops based on constraints
  src/murmur/ServerDB.cpp
Labels: bug, server

#4389 CI(installer): Only build a few cultures by default
  scripts/Create-Win32InstallerMUI.ps1
Labels: ci

#4377 CI(azure-pipelines): add 32 bit Windows build
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/build_windows.bat
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
  .ci/travis-ci/script.bash
Labels: ci

#4392 FIX(server): Packet size issues
  src/murmur/Server.cpp
Labels: bug, server

#4394 FIX(client): Discard oversized UDP packets
  src/mumble/ServerHandler.cpp
Labels: backport-needed, bug, client

#4395 CI(azure): Don't overwrite build artifacts
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
  .ci/azure-pipelines/steps_windows.yml
Labels: ci

#4397 Backport "FIX(server): Reorder old table drops based on constraints"
  src/murmur/ServerDB.cpp
Labels: backport

#4396 CI(windows): Zip all PDB files
  .ci/azure-pipelines/steps_windows.yml
Labels: ci

#4398 Backport "FIX(ui): Make chatwidget max height >= than its minimum height"
  src/mumble/CustomElements.cpp
Labels: backport

#4399 Backport "FIX(server): Packet size issues"
  src/murmur/Server.cpp
Labels: backport

#4400 Backport "FIX(client): Discard oversized UDP packets"
  src/mumble/ServerHandler.cpp
Labels: backport

#4401 MAINT: Bump version to 1.3.3
  g15helper/g15helper.plist
  g15helper/g15helper.rc
  installer/Settings.wxi
  macx/common.pri
  macx/osax/osax.plist
  overlay/mumble_ol.rc
  overlay/overlay-shared.pro
  overlay/overlay_exe/overlay_exe.rc
  overlay_gl/overlay_gl.pro
  overlay_winx64/mumble_ol.rc
  overlay_winx64/overlay_exe_winx64/overlay_exe.rc
  src/mumble.pri
  src/mumble/mumble.plist
  src/mumble/mumble.rc
  src/mumble/mumble_dll.rc
  src/murmur/murmur.plist
  src/murmur/murmur.rc
Labels: release-management

#4403 MAINT: Disable warnings for 3rdparty projects
  CMakeLists.txt
  cmake/project-utils.cmake
  src/mumble/CMakeLists.txt
Labels: build

#4404 CI(azure-pipelines): switch to latest build environment
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
Labels: ci, release-management

#4410 MAINT(cmake): Only return compilable targets
  cmake/project-utils.cmake
Labels: build

#4411 MAINT(cmake): Enable DBus for the client
  src/mumble/CMakeLists.txt
Labels: bug, build

#4412 FIX(cmake): define "MUMBLE_VERSION_STRING" to short version (e.g. "1.4.0")
  src/CMakeLists.txt
Labels: build

#4413 FIX(cmake): set CMAKE_WIX_UPGRADE_GUID and generate CMAKE_WIX_PRODUCT_GUID
  cmake/packaging.cmake
Labels: build, installer, release-management, windows

#4414 FIX(certificate): Retrieve QSslConfiguration after setting CA
  src/murmur/Server.cpp
Labels: bug, server

#4408 FEAT(client): print extended error when QOSRemoveSocketFromFlow() fails
  src/mumble/ServerHandler.cpp
Labels: client, windows

#4423 FIX(client): Compile error without manual plugin
  src/mumble/AudioOutput.cpp
  src/mumble/AudioOutput.h
  src/mumble/Plugins.cpp
Labels: bug, build

#4416 CI(azure): Disable environment caching
  .ci/azure-pipelines/steps_macos.yml
  .ci/azure-pipelines/steps_windows.yml
Labels: ci

#4426 FIX(packaging): Enable mac-script to run multiple times
  macx/scripts/osxdist.py
Labels: ci, release-management

#4429 FIX(client): define and export "MumbleMain" also in debug builds
  src/mumble/CMakeLists.txt
  src/mumble/main.cpp
Labels: build, windows

#4438 FEAT(talking-ui): Save last position
  src/mumble/MainWindow.cpp
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/main.cpp
Labels: client, feature-request, ui

#4442 CI(macOS): Use axel instead of wget
  .ci/azure-pipelines/install-environment_macos.bash
Labels: ci

#4443 CI: Show progress for decompressing
  .ci/azure-pipelines/extractWithProgress.bash
  .ci/azure-pipelines/install-environment_macos.bash
Labels: ci

#4439 FEAT(client, mainwindow): Show volume adjustments
  src/mumble/AudioOutput.cpp
  src/mumble/ClientUser.cpp
  src/mumble/ClientUser.h
  src/mumble/LookConfig.cpp
  src/mumble/LookConfig.ui
  src/mumble/Messages.cpp
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/TalkingUI.cpp
  src/mumble/TalkingUI.h
  src/mumble/UserLocalVolumeDialog.cpp
  src/mumble/UserModel.cpp
  src/mumble/UserModel.h
  src/mumble/mumble_en.ts
Labels: client, feature-request, ui

#4441 FIX(cmake): Set QT_RESTRICTED_CAST_FROM_ASCII
  src/CMakeLists.txt
  src/mumble/CMakeLists.txt
  src/murmur/CMakeLists.txt
  src/murmur/Messages.cpp
  src/murmur/Meta.cpp
  src/murmur/PBKDF2.cpp
  src/murmur/Server.cpp
  src/murmur/UnixMurmur.cpp
Labels: build, code

#4446 BUILD: CMake usability enhancements
  CMakeLists.txt
  COMMIT_GUIDELINES.md
  cmake/pkg-utils.cmake
Labels: build
