Repository mumble-voip/mumble, pull requests merged in 2021-03, with the labels that each got.

#4791 BUILD(cmake): Fix pkg search on case-insensitive filesystems
  cmake/pkg-utils.cmake
Labels: build, macOS

#4815 CI(windows): Increase timeout
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
Labels: ci

#4814 FIX(mac, audio): Identify output device
  src/mumble/CoreAudio.mm
  src/mumble/Settings.cpp
Labels: audio, bug, macOS

#4816 MAINT(docker): Make Dockerfile working again
  Dockerfile
Labels: release-management

#4817 FIX(Server): Unauthenticated connections no longer add to user count
  src/murmur/Messages.cpp
  src/murmur/Server.cpp
Labels: bug, server

#4809 FEAT(server, ice): Ability to broadcast welcome text
  docs/dev/ExtendingTheIceInterface.md
  src/murmur/Murmur.ice
  src/murmur/MurmurI.h
  src/murmur/MurmurIce.cpp
  src/murmur/MurmurIceWrapper.cpp
  src/murmur/RPC.cpp
  src/murmur/Server.h
Labels: ice, server

#4819 FIX(server): Ctrl-C leaves UDP port open.
  src/murmur/main.cpp
Labels: backport-needed, bug, server

#4821 CI: Omit online tests
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/build_windows.bat
  .ci/travis-ci/before_install.bash
  .ci/travis-ci/script.bash
  .github/workflows/build.yml
Labels: ci

#4828 CI(windows): Use aria2 for downloading
  .ci/azure-pipelines/install-environment_windows.ps1
Labels: ci

#4811 MAINT: Replace updatetranslations script and update translation files
  .ci/azure-pipelines/assertNoTranslationChanges.sh
  .ci/azure-pipelines/install-environment_linux_translations.bash
  scripts/updatetranslations.py
  scripts/updatetranslations.sh
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: translation

#4831 MAINT: Add Weblate and translation notice to README.md
  README.md
Labels: translation

#4832 TRANSLATION: Recover lost translations from Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_no.ts
Labels: translation

#4836 BUILD(cmake): Fix unity build failure
  cmake/qt-utils.cmake
Labels: build

#4839 TRANSLATION: Add new translation for Sinhala (si)
  src/mumble/mumble_si.ts
Labels: translation

#4840 CI(macOS): Fix test cases not being found
  .ci/azure-pipelines/steps_macos.yml
Labels: ci

#4845 BUILD(cmake): Fix unity build issue
  src/mumble/CMakeLists.txt
Labels: build

#4837 MAINT: Small fixes and cleanup
  scripts/updatetranslations.py
Labels: translation

#4820 FEAT(client): Improvements to local translation dir search
  src/mumble/CMakeLists.txt
  src/mumble/Translations.cpp
  src/mumble/Translations.h
  src/mumble/main.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, feature-request, translation

#4859 BUILD: Bumped overlay version to 1.3.4 as well
  overlay_gl/overlay_gl.pro
Labels: build

#4864 FIX(client): Make translations work again
  src/mumble/Translations.cpp
  src/mumble/Translations.h
  src/mumble/main.cpp
Labels: bug, translation

#4867 FIX(client): Make button in config dialog translatable
  src/mumble/ConfigDialog.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: translation

#4869 FIX(client): Qt translations not found
  src/mumble/Translations.cpp
Labels: bug, translation

#4872 FIX(client): Use Utf8 for name field in certificat
  src/SelfSignedCertificate.cpp
Labels: backport-needed, bug, client

#4868 FIX(positional-audio): Fix and revamp Call of Duty 2 plugin
  plugins/cod2/CMakeLists.txt
  plugins/cod2/cod2.cpp
Labels: client, positional audio

#4875 FIX(client, ui): Ordering of Users inconsistent
  src/User.cpp
Labels: backport-needed, bug, client

#4884 FIX(client, talking-ui): No users being added
  src/mumble/TalkingUI.cpp
Labels: bug, client

#4886 FIX(Server): Prevent multiple Sessions with ID 0
  src/murmur/Server.cpp
Labels: server

#4891 FEAT(client, ui): Revamped server information dialog
  src/mumble/CMakeLists.txt
  src/mumble/MainWindow.cpp
  src/mumble/ServerInformation.cpp
  src/mumble/ServerInformation.h
  src/mumble/ServerInformation.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, ui

#4878 Translations update from Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#4892 MAINT/CI: Various improvements
  .ci/azure-pipelines/assertNoTranslationChanges.sh
  .github/workflows/checks.yml
  3rdPartyLicenses/boost_license.txt
  3rdPartyLicenses/libdaemon_license.txt
  3rdPartyLicenses/libjpeg_turbo_license.txt
  3rdPartyLicenses/mariadb_c_connector_license.txt
  3rdPartyLicenses/sqlite3_license.txt
  3rdPartyLicenses/zlib_license.txt
  helpers/vcpkg/ports/zeroc-ice/CONTROL
  scripts/updatetranslations.py
  src/mumble/qttranslations/translations.conf
Labels: ci
