Repository mumble-voip/mumble, pull requests merged in 2021-02, with the labels that each got.

#4729 TRANSLATION: Remove empty translations
  src/mumble/CMakeLists.txt
  src/mumble/mumble_be.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_vi.ts
  src/mumble/translations.pri
Labels: translation

#4731 TRANSLATION: Remove empty nl_BE file
  src/mumble/CMakeLists.txt
  src/mumble/mumble_nl_BE.ts
Labels: translation

#4720 FIX(ocb2): Work around packet loss due to OCB2 XEX* mitigation
  src/crypto/CryptStateOCB2.cpp
  src/crypto/CryptStateOCB2.h
  src/tests/TestCrypt/TestCrypt.cpp
Labels: backport-needed, bug

#4722 FEAT(client): Introduce GlobalShortcutButtons, for better shortcut management
  src/mumble/AudioWizard.cpp
  src/mumble/AudioWizard.h
  src/mumble/AudioWizard.ui
  src/mumble/CMakeLists.txt
  src/mumble/GlobalShortcut.cpp
  src/mumble/GlobalShortcut.h
  src/mumble/GlobalShortcutButtons.cpp
  src/mumble/GlobalShortcutButtons.h
  src/mumble/GlobalShortcutButtons.ui
  src/mumble/GlobalShortcut_macx.h
  src/mumble/GlobalShortcut_macx.mm
  src/mumble/GlobalShortcut_unix.cpp
  src/mumble/GlobalShortcut_unix.h
  src/mumble/GlobalShortcut_win.cpp
  src/mumble/GlobalShortcut_win.h
  src/mumble/mumble_en.ts
Labels: GlobalShortcuts, client

#4733 FIX(client): Only allow "http" and "https" schemes in ConnectDialog for web page
  src/mumble/ConnectDialog.cpp
  src/mumble/mumble_en.ts
Labels: backport-needed, client

#4737 Backport "FIX(client): Ancient notification icon names"
  src/mumble/Log_unix.cpp
Labels: backport

#4736 Backport "Use qInfo instead of qFatal for normal logging"
  src/murmur/main.cpp
Labels: backport

#4739 Backport "FIX(client): Only allow "http"/"https" for URLs in ConnectDialog"
  src/mumble/ConnectDialog.cpp
  src/mumble/mumble_en.ts
Labels: backport

#4738 Backport "FIX(ocb2): Work around packet loss due to OCB2 XEX* mitigation"
  src/CryptState.cpp
  src/CryptState.h
  src/tests/TestCrypt/TestCrypt.cpp
Labels: backport

#4741 FIX(installer): Change version regex so that it accepts multiple digits
  installer/ClientInstaller.cs
  installer/ServerInstaller.cs
Labels: build, installer

#4746 CI: Update to FreeBSD 12.2
  .cirrus.yml
Labels: ci

#4694 Experimental Echo Cancellation for MacOS
  scripts/updatetranslations.sh
  src/mumble/ALSAAudio.cpp
  src/mumble/ASIOInput.cpp
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioInput.cpp
  src/mumble/AudioInput.h
  src/mumble/AudioInput.ui
  src/mumble/AudioWizard.cpp
  src/mumble/AudioWizard.h
  src/mumble/CMakeLists.txt
  src/mumble/CoreAudio.h
  src/mumble/CoreAudio.mm
  src/mumble/EchoCancelOption.h
  src/mumble/JackAudio.cpp
  src/mumble/OSS.cpp
  src/mumble/PAAudio.cpp
  src/mumble/PulseAudio.cpp
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/WASAPI.cpp
  src/mumble/mumble_en.ts
Labels: audio, client, feature-request, macOS

#3571 FEAT: Improve OSInfo so that architecture and OS are properly reported
  src/OSInfo.cpp
  src/OSInfo.h
Labels: linux

#4754 FEAT(client): Add "starttalking" and "stoptalking" to the socket RPC interface
  src/mumble/SocketRPC.cpp
  src/mumble/main.cpp
  src/mumble/mumble_en.ts
Labels: client

#4753 CI(azure): Use version & commit hash as identifier for build number
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/build_windows.bat
Labels: ci, release-management

#4760 MAINT(github): Update PR template
  .github/pull_request_template.md
Labels: github

#4762 Fix echo cancellation setting not saved
  src/mumble/Settings.cpp
Labels: bug, client

#4767 FIX(client): Default echo cancel setting not loaded correctly
  src/mumble/Settings.cpp
Labels: bug, client

#4763 BUILD(versioning): Remove tag logic, implement "--revision", "--format" and "--type" options in mumble-version.py
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/build_windows.bat
  scripts/mumble-version.py
Labels: build, ci

#4764 FIX(talking-ui): Crash after rename
  src/mumble/TalkingUI.cpp
Labels: bug, client

#4770 CI(azure): Update to latest vcpkg environment
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
Labels: ci

#4765 Fixes for building on ARM Macs
  CMakeLists.txt
  src/mumble/CoreAudio.mm
  src/mumble/GlobalShortcut_macx.mm
  src/mumble/MainWindow.cpp
  src/mumble/mumble.plist.in
  src/mumble/os_macx.mm
Labels: build, macOS

#4774 BUILD(cmake): Add sndfile library/target name
  src/mumble/CMakeLists.txt
Labels: build

#4777 FIX(client, accessibility): Duplicate keyboard shortcuts
  src/mumble/ConnectDialog.cpp
  src/mumble/mumble_en.ts
Labels: accessibility, bug, client

#4779 FIX(client): Don't show URL password in clear text
  src/mumble/MainWindow.cpp
Labels: client, ui

#4782 CI: Make windows scripts more robust
  .ci/azure-pipelines/install-environment_windows.ps1
Labels: ci

#4778 Fix url version
  src/Version.cpp
  src/mumble/MainWindow.cpp
  src/mumble/mumble_en.ts
Labels: bug, client

#4789 CI(macos): Fix release ID not being set for macOS package
  .ci/azure-pipelines/build_macos.bash
Labels: build, ci

#4803 CI(macOS): Use mutliple attempts for downloads
  .ci/azure-pipelines/install-environment_macos.bash
Labels: ci

#4804 CI: Added commit-style check
  .github/workflows/check_commit_style.py
  .github/workflows/check_commit_style.yml
  .gitignore
Labels: ci

#4806 DOCS: Added description of Developer console
  docs/DeveloperConsole.md
  docs/media/images/Mumble_DeveloperConsole.png
  docs/media/images/Mumble_Settings_DeveloperMenu.png
Labels: documentation
