Repository mumble-voip/mumble, pull requests merged in 2021-05, with the labels that each got.

#4942 DOCS: Fixed typos
  COMMIT_GUIDELINES.md
  docs/dev/build-instructions/build_static.md
Labels: documentation

#4954 CHANGE(client): Default min volume to 25%
  src/mumble/AudioOutput.ui
  src/mumble/Settings.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client

#4958 FEAT(client): Global shortcut to toggle TalkingUI
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, feature-request

#4972 TRANSLATION: Add new language Albanian (sq)
  src/mumble/CMakeLists.txt
  src/mumble/mumble_sq.ts
Labels: translation

#4981 REFAC(client): Don't use deprecated mutex ctor
  src/mumble/Plugin.cpp
  src/mumble/ServerHandler.cpp
Labels: code

#4974 FIX(client): Properly show currently selected audio device in settings dialog
  src/mumble/ALSAAudio.cpp
  src/mumble/ASIOInput.cpp
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioInput.h
  src/mumble/AudioOutput.h
  src/mumble/CoreAudio.h
  src/mumble/CoreAudio.mm
  src/mumble/JackAudio.cpp
  src/mumble/OSS.cpp
  src/mumble/PAAudio.cpp
  src/mumble/PAAudio.h
  src/mumble/PulseAudio.cpp
  src/mumble/WASAPI.cpp
  src/mumble/WASAPI.h
Labels: client, ui

#4982 FIX(client): Mismatched delete in ProcessResolver
  src/ProcessResolver.cpp
  src/ProcessResolver.h
  src/mumble/PluginManager.cpp
Labels: bug, client

#4976 FIX(client): Windows loading/saving shortcuts
  src/mumble/GlobalShortcut_win.cpp
  src/mumble/GlobalShortcut_win.h
  src/mumble/PluginManager.cpp
  src/mumble/Settings.cpp
Labels: bug, client

#4985 FIX(translation): Wrong wording in search dialog
  src/mumble/SearchDialog.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: bug

#4991 FIX(client, ui): TalkingUI font not scaling properly
  src/mumble/widgets/MultiStyleWidgetWrapper.cpp
  src/mumble/widgets/MultiStyleWidgetWrapper.h
Labels: bug, client, ui

#4997 DOCS: Added info about Poco dependency
  docs/dev/build-instructions/build_linux.md
  docs/dev/build-instructions/build_macos.md
Labels: documentation

#4995 FEAT(client): Revamp positional audio settings page
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioConfigDialog.h
  src/mumble/AudioOutput.cpp
  src/mumble/AudioOutput.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, feature-request, ui

#4994 FIX(client): Echo cancellation options not translated
  cmake/os.cmake
  src/mumble/AudioConfigDialog.cpp
  src/mumble/CMakeLists.txt
  src/mumble/EchoCancelOption.cpp
  src/mumble/EchoCancelOption.h
Labels: bug, client, translation

#4998 Translations update from Weblate
  src/mumble/mumble_ko.ts
Labels: translation

#5000 FIX(client): Don't escape characters in URL targets
  src/mumble/Markdown.cpp
Labels: bug, client

#5003 FIX(server): ChannelListener IDs colliding across VServers
  src/ChannelListener.cpp
  src/ChannelListener.h
  src/ChannelListenerManager.cpp
  src/ChannelListenerManager.h
  src/mumble/AudioOutput.cpp
  src/mumble/CMakeLists.txt
  src/mumble/Global.cpp
  src/mumble/Global.h
  src/mumble/ListenerLocalVolumeDialog.cpp
  src/mumble/MainWindow.cpp
  src/mumble/Messages.cpp
  src/mumble/TalkingUI.cpp
  src/mumble/UserModel.cpp
  src/mumble/main.cpp
  src/murmur/CMakeLists.txt
  src/murmur/Messages.cpp
  src/murmur/MurmurIce.cpp
  src/murmur/RPC.cpp
  src/murmur/Server.cpp
  src/murmur/Server.h
Labels: bug, server

#5005 FORMAT: Run clang-format 10 on all source files
  src/mumble/AudioOutput.cpp
  src/mumble/Global.cpp
  src/mumble/Global.h
  src/mumble/ListenerLocalVolumeDialog.cpp
  src/mumble/MainWindow.cpp
  src/mumble/TalkingUI.cpp
  src/mumble/UserModel.cpp
  src/mumble/main.cpp
  src/murmur/Messages.cpp
  src/murmur/Server.cpp
Labels: code

#5004 Translations update from Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#5007 BUILD(macos): Fix package script failing
  COMMIT_GUIDELINES.md
  macx/scripts/osxdist.py
  scripts/commitMessage/CommitMessage.py
  scripts/generateChangelog.py
Labels: build, macOS

#5009 Backport "BUILD(macos): Fix package script failing"
  COMMIT_GUIDELINES.md
  macx/scripts/osxdist.py
  scripts/commitMessage/CommitMessage.py
  scripts/generateChangelog.py
Labels: backport

#5010 BUILD: Fixes for Ubuntu 20.04 ppa build
  3rdparty/celt-0.7.0-build/CMakeLists.txt
  plugins/PluginComponents_v_1_0_x.h
  src/CMakeLists.txt
  src/mumble/GlobalShortcut_unix.h
Labels: build

#5013 CHANGE(client, ui): Display unit as suffix in SpinBox
  src/mumble/AudioOutput.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, ui

#5015 CI: Fix PR checks for backports
  .github/workflows/check_commit_style.py
  .github/workflows/pr-checks.yml
Labels: ci

#5008 Translations update from Weblate
  src/mumble/mumble_he.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
Labels: backport-needed, translation

#5016 Backport "CI: Fix PR checks for backports"
  .github/workflows/check_commit_style.py
  .github/workflows/pr-checks.yml
Labels: backport

#5017 Backport "CHANGE(client, ui): Display unit as suffix in SpinBox"
  src/mumble/AudioOutput.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport

#5014 Backport "BUILD: Fixes for Ubuntu 20.04 ppa build"
  3rdparty/celt-0.7.0-build/CMakeLists.txt
  plugins/PluginComponents_v_1_0_x.h
  src/CMakeLists.txt
  src/mumble/GlobalShortcut_unix.h
Labels: backport

#5018 Backport "Translations update from Weblate"
  src/mumble/mumble_he.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
Labels: backport

#5027 DOCS: Fix typo in developer console description
  docs/DeveloperConsole.md
Labels: documentation

#5028 DOCS: Link WixSharp to latest releases page
  docs/dev/build-instructions/build_installer.md
Labels: documentation

#5032 DOCS: Mention Cpp14 requirement
  docs/dev/build-instructions/README.md
Labels: documentation

#5031 FIX(server, unix): DB corruption due to missing locks
  src/murmur/main.cpp
Labels: bug, server

#5044 Backport "FIX(server, unix): DB corruption due to missing locks"
  src/murmur/main.cpp
Labels: backport

#5035 FIX(client): Positional audio not working properly after canceling audio wizard
  src/mumble/AudioWizard.cpp
Labels: audio, client, positional audio

#5038 FEAT(client): Do not play the mute cue when push-to-muted
  src/mumble/AudioInput.cpp
Labels: client, feature-request

#5029 Make posted images slightly larger to improve legibility
  src/mumble/Log.cpp
Labels: client

#5049 Backport "BUILD(windows): Fix missing include"
  src/mumble/GlobalShortcut_win.cpp
Labels: backport

#5048 BUILD(windows): Fix missing include
  src/mumble/GlobalShortcut_win.cpp
Labels: build

#5046 Backport "FIX(client): Positional audio not working properly after canceling audio wizard"
  src/mumble/AudioWizard.cpp
Labels: backport

#5047 Backport "FEAT(client): Do not play the mute cue when push-to-muted"
  src/mumble/AudioInput.cpp
Labels: backport

#5050 Backport "CHANGE(client): Resize posted images to 800x600 instead of 420x270"
  src/mumble/Log.cpp
Labels: backport

#5034 REFAC(plugin): Rename plugin ID parameter
  plugins/MumblePlugin_v_1_0_x.h
Labels: code

#5059 DOCS(installer): Fixup and extend installer build documentation
  docs/dev/build-instructions/build_installer.md
Labels: build, documentation

#5054 MAINT: Update copyright notice to 2021 (Part III)
  installer/Mumble.rtf
Labels: backport-needed

#5066 Backport "MAINT: Update copyright notice to 2021 (Part III) (#5054)" to 1.4.x
  installer/Mumble.rtf
Labels: backport

#5068 DOCS: Mention BUILD_NUMBER for building installer
  docs/dev/build-instructions/build_installer.md
Labels: documentation

#5063 DOCS(build): Add a missing dependency to static build instructions.
  docs/dev/build-instructions/build_static.md
Labels: documentation

#5062 BUILD(cmake): Rename server to mumble-server
  installer/ServerInstaller.cs
  src/murmur/CMakeLists.txt
Labels: build

#5071 Backport "BUILD(cmake): Rename server to mumble-server (#5062)" to 1.4.x
  installer/ServerInstaller.cs
  src/murmur/CMakeLists.txt
Labels: backport

#5019 Translations update from Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#5073 Backport "Translations update from Weblate" to 1.4.x
  src/mumble/mumble_de.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
Labels: backport

#4808 FEAT(client): Message Thresholding
  src/mumble/Log.cpp
  src/mumble/Log.h
  src/mumble/Log.ui
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, feature-request

#5079 FIX(pipewire): Do not initialize stream with 0 channels
  src/mumble/Settings.cpp
Labels: audio, client

#5080 Backport "FIX(pipewire): Do not initialize stream with 0 channels"
  src/mumble/Settings.cpp
Labels: backport
