Repository mumble-voip/mumble, pull requests merged in 2021-01, with the labels that each got.

#4663 FIX(positional-audio): Update Among Us plugin to work with v2020.12.09s
  plugins/amongus/Game.cpp
Labels: client, positional audio

#4661 FIX(client): Image not supported error message wrongly displayed,
  src/mumble/CustomElements.cpp
Labels: bug, client

#4667 FEAT(client): Added DBus calls to toggle mute and deaf state.
  src/mumble/DBus.cpp
  src/mumble/DBus.h
Labels: client, feature-request

#4671 FIX(client,ui): Crash by pressing Esc in nickname dialog
  src/CMakeLists.txt
  src/QtUtils.cpp
  src/QtUtils.h
  src/mumble/MainWindow.h
  src/mumble/UserLocalNicknameDialog.cpp
  src/mumble/UserLocalNicknameDialog.h
Labels: bug, client, ui

#4669 BUILD(versioning): Make use of the 4th part (build/tweak) of the version
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/build_windows.bat
  .ci/travis-ci/script.bash
  CMakeLists.txt
  g15helper/g15helper.rc.in
  overlay/CMakeLists.txt
  overlay/mumble_ol.rc.in
  overlay/overlay_exe/overlay_exe.rc.in
  overlay_winx64/mumble_ol.rc.in
  overlay_winx64/overlay_exe_winx64/overlay_exe.rc.in
  scripts/mumble-version.py
  src/CMakeLists.txt
  src/Version.h
  src/mumble/mumble.rc.in
  src/mumble/mumble_dll.rc.in
  src/mumble_exe/CMakeLists.txt
  src/murmur/CMakeLists.txt
  src/murmur/murmur.rc.in
Labels: build, ci, release-management

#4677 CI(azure): Fix build number system
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/build_windows.bat
  .ci/azure-pipelines/main.yml
Labels: ci

#4688 FIX(client,ui): Channel description via lock icon
  src/mumble/UserView.cpp
Labels: bug, client, ui

#4689 FIX(server): Older clients not being warned about ChannelListener
  src/murmur/Messages.cpp
Labels: bug, server

#4690 FEAT(client): Add new icons to "What's this?"
  src/mumble/UserModel.cpp
  src/mumble/mumble_en.ts
Labels: client, ui

#4705 FIX(client): Ancient notification icon names
  src/mumble/Log_unix.cpp
Labels: backport-needed, bug, client, linux

#4711 CI(azure): Export BUILD_NUMBER_TOKEN correctly
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/build_windows.bat
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
  .ci/azure-pipelines/steps_linux.yml
  .ci/azure-pipelines/steps_macos.yml
  .ci/azure-pipelines/steps_windows.yml
Labels: ci

#4718 CI(azure): Fix VERSION variable not being expanded correctly in curl call
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/build_windows.bat
Labels: ci

#4713 BUILD(installer): Include g15-helper
  installer/ClientInstaller.cs
Labels: installer

#4721 REFAC(client): Move CompletablePage class into dedicated file set
  src/mumble/AudioWizard.cpp
  src/mumble/AudioWizard.h
  src/mumble/AudioWizard.ui
  src/mumble/CMakeLists.txt
  src/mumble/Cert.ui
  src/mumble/widgets/CompletablePage.cpp
  src/mumble/widgets/CompletablePage.h
Labels: client, code

#4724 CI(windows): Fix build number fetching script
  .ci/azure-pipelines/build_windows.bat
Labels: ci
