Repository mumble-voip/mumble, pull requests merged in 2021-09, with the labels that each got.

#5250 Backport "BUILD(cmake): Increase OSX deployment target (#5045)" to 1.4.x
  CMakeLists.txt
  src/mumble/GlobalShortcut_macx.mm
  src/mumble/Overlay.cpp
Labels: backport

#5251 FEAT(client): Add opus as output format for recording
  src/mumble/CMakeLists.txt
  src/mumble/VoiceRecorder.cpp
  src/mumble/VoiceRecorder.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, feature-request

#5243 Translations update from Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_TW.ts
Labels: translation

#5254 TRANSLATION: Backport translations
  src/mumble/mumble_el.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_zh_TW.ts
Labels: translation

#5253 DOCS: Backporting translations
  docs/dev/maintenance/BackportTranslations.md
Labels: documentation

#5259 MAINT(Dockerfile): Backport most recent improvements
  Dockerfile
Labels: backport

#5260 MAINT(docker): Update server executable name (backported)
  Dockerfile
Labels: backport
