Repository mumble-voip/mumble, pull requests merged in 2021-06, with the labels that each got.

#5083 Backport "FIX(audiowizard): Reset AudioOutput ownership before restartAudio() (#5082)" to 1.4.x
  src/mumble/AudioWizard.cpp
Labels: backport

#5077 BUILD(windows): Fix missing include
  plugins/amongus/amongus.cpp
  plugins/cod2/cod2.cpp
  plugins/se/se.cpp
Labels: code

#5088 FIX(client, ui): Use proper name for fallback theme
  src/mumble/Themes.cpp
Labels: bug, client, ui

#5089 Backport "BUILD(windows): Fix missing include (#5077)" to 1.4.x
  plugins/amongus/amongus.cpp
  plugins/cod2/cod2.cpp
  plugins/se/se.cpp
Labels: backport

#5069 BUILD(installer): Include binaries only if built
  installer/ClientInstaller.cs
  src/mumble_exe/CMakeLists.txt
Labels: build, installer

#5090 Backport "BUILD(installer): Include binaries only if built " to 1.4.x
  installer/ClientInstaller.cs
  src/mumble_exe/CMakeLists.txt
Labels: backport

#5084 REFAC(client): Remove unnecessary include
  plugins/mumble_positional_audio_utils.h
Labels: code

#5087 FIX(client): Use ReadProcessMemory() instead of Toolhelp32ReadProcessMemory()
  plugins/HostWindows.cpp
  plugins/HostWindows.h
Labels: backport-needed, client, positional audio

#5092 Backport "FIX(client): Use ReadProcessMemory() instead of Toolhelp32ReadProcessMemory() (#5087)" to 1.4.x
  plugins/HostWindows.cpp
  plugins/HostWindows.h
Labels: backport

#5096 DOCS: Document new plugin system
  README.md
  docs/dev/plugins/Bundling.md
  docs/dev/plugins/CreatePlugin.md
  docs/dev/plugins/Debugging.md
  docs/dev/plugins/LanguageBindings.md
  docs/dev/plugins/MumbleAPI.md
  docs/dev/plugins/PluginAPI.md
  docs/dev/plugins/PluginLifecycle.md
  docs/dev/plugins/PositionalAudioPlugin.md
  docs/dev/plugins/README.md
  docs/dev/plugins/ResourceManagement.md
  docs/dev/plugins/Versioning.md
Labels: documentation

#5095 BUILD(plugins): Make API header compile with C again
  plugins/MumbleAPI_v_1_0_x.h
  plugins/PluginComponents_v_1_0_x.h
  plugins/testPlugin/testPlugin.cpp
  src/Version.cpp
  src/Version.h
  src/mumble/API_v_1_0_x.cpp
  src/mumble/ConnectDialog.cpp
  src/mumble/LegacyPlugin.cpp
  src/mumble/MainWindow.cpp
  src/mumble/Messages.cpp
  src/mumble/Plugin.cpp
  src/mumble/PluginConfig.cpp
  src/mumble/PluginInstaller.cpp
  src/mumble/PluginManager.cpp
  src/mumble/ServerHandler.cpp
  src/mumble/ServerInformation.cpp
  src/mumble/UserInformation.cpp
  src/murmur/Messages.cpp
  src/murmur/Meta.cpp
  src/murmur/RPC.cpp
  src/murmur/Server.cpp
Labels: code

#5093 MAINT(macOS): Add client entitlements plist, for hardened runtime to work
  src/mumble/mumble.entitlements.plist
Labels: build, macOS

#5104 Backport "BUILD(plugins): Make API header compile with C again" to 1.4.x
  plugins/MumbleAPI_v_1_0_x.h
  plugins/PluginComponents_v_1_0_x.h
  plugins/testPlugin/testPlugin.cpp
  src/Version.cpp
  src/Version.h
  src/mumble/API_v_1_0_x.cpp
  src/mumble/ConnectDialog.cpp
  src/mumble/LegacyPlugin.cpp
  src/mumble/MainWindow.cpp
  src/mumble/Messages.cpp
  src/mumble/Plugin.cpp
  src/mumble/PluginConfig.cpp
  src/mumble/PluginInstaller.cpp
  src/mumble/PluginManager.cpp
  src/mumble/ServerHandler.cpp
  src/mumble/ServerInformation.cpp
  src/mumble/UserInformation.cpp
  src/murmur/Messages.cpp
  src/murmur/Meta.cpp
  src/murmur/RPC.cpp
  src/murmur/Server.cpp
Labels: backport

#5105 DOCS(plugins): Fix missing pointer star in example
  docs/dev/plugins/PositionalAudioPlugin.md
Labels: documentation

#5101 Backport "DOCS: Document new plugin system (#5096)" to 1.4.x
  README.md
  docs/dev/plugins/Bundling.md
  docs/dev/plugins/CreatePlugin.md
  docs/dev/plugins/Debugging.md
  docs/dev/plugins/LanguageBindings.md
  docs/dev/plugins/MumbleAPI.md
  docs/dev/plugins/PluginAPI.md
  docs/dev/plugins/PluginLifecycle.md
  docs/dev/plugins/PositionalAudioPlugin.md
  docs/dev/plugins/README.md
  docs/dev/plugins/ResourceManagement.md
  docs/dev/plugins/Versioning.md
Labels: backport

#5108 Backport "DOCS(plugins): Fix missing pointer star in example (#5105)" to 1.4.x
  docs/dev/plugins/PositionalAudioPlugin.md
Labels: backport

#5106 FIX(client): PluginInstaller unable to extract zips
  src/mumble/PluginInstaller.cpp
Labels: bug, client

#5109 Backport "FIX(client): PluginInstaller unable to extract zips (#5106)" to 1.4.x
  src/mumble/PluginInstaller.cpp
Labels: backport

#5045 BUILD(cmake): Increase OSX deployment target
  CMakeLists.txt
  src/mumble/GlobalShortcut_macx.mm
  src/mumble/Overlay.cpp
Labels: build

#5111 FIX(server): uiSession being used before assignment
  src/murmur/Messages.cpp
Labels: backport-needed, bug, server

#5112 Backport "FIX(server): uiSession being used before assignment (#5111)" to 1.4.x
  src/murmur/Messages.cpp
Labels: backport

#5114 FIX(client, plugin-api): onAudioOutputAboutToPlay
  src/mumble/PluginManager.cpp
Labels: backport-needed, bug, client

#5103 REFAC(positional-audio): Use new plugin API in Among Us plugin
  plugins/amongus/Game.cpp
  plugins/amongus/Game.h
  plugins/amongus/amongus.cpp
Labels: client, positional audio

#5113 FIX(client, plugin-api): requestLocalUserTransmissionMode
  plugins/MumbleAPI_v_1_0_x.h
  src/mumble/API_v_1_0_x.cpp
Labels: bug, client

#5115 Backport "FIX(client, plugin-api): onAudioOutputAboutToPlay (#5114)" to 1.4.x
  src/mumble/PluginManager.cpp
Labels: backport

#5116 Backport "FIX(client, plugin-api): requestLocalUserTransmissionMode (#5113)" to 1.4.x
  plugins/MumbleAPI_v_1_0_x.h
  src/mumble/API_v_1_0_x.cpp
Labels: backport

#5074 Translations update from Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#5094 FEAT(client): Positional interaural delay
  src/mumble/Audio.h
  src/mumble/AudioOutput.cpp
  src/mumble/AudioOutputSample.cpp
  src/mumble/AudioOutputSpeech.cpp
  src/mumble/AudioOutputUser.h
Labels: client, feature-request, positional audio

#5117 FIX(client): Ambiguity in plugin installer
  CMakeLists.txt
  cmake/TargetArch.cmake
  docs/dev/plugins/Bundling.md
  src/mumble/CMakeLists.txt
  src/mumble/PluginInstaller.cpp
  src/mumble/PluginManifest.cpp
  src/mumble/PluginManifest.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
  src/mumble_exe/CMakeLists.txt
  src/murmur/CMakeLists.txt
Labels: bug, client

#5123 Backport "FIX(client): Ambiguity in plugin installer"
  CMakeLists.txt
  cmake/TargetArch.cmake
  docs/dev/plugins/Bundling.md
  src/mumble/CMakeLists.txt
  src/mumble/PluginInstaller.cpp
  src/mumble/PluginManifest.cpp
  src/mumble/PluginManifest.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
  src/mumble_exe/CMakeLists.txt
  src/murmur/CMakeLists.txt
Labels: backport

#5124 CI: Add CodeQL analysis
  .github/workflows/code-ql.yml
Labels: ci

#5125 FEAT(positional-audio): Add support for DT_GNU_HASH, to locate exported symbols
  plugins/ProcessLinux.cpp
Labels: feature-request, positional audio

#5126 FIX(positional-audio): Update Among Us plugin to work with v2021.6.15s
  plugins/amongus/structs.h
Labels: positional audio

#5129 BUILD(cmake): Reorganize how plugins are handled
  plugins/CMakeLists.txt
  plugins/amongus/Game.cpp
  plugins/aoc/aoc.cpp
  plugins/arma2/arma2.cpp
  plugins/bf1/bf1.cpp
  plugins/bf1942/bf1942.cpp
  plugins/bf2/bf2.cpp
  plugins/bf2142/bf2142.cpp
  plugins/bf3/bf3.cpp
  plugins/bf4/bf4.cpp
  plugins/bf4_x86/bf4_x86.cpp
  plugins/bfbc2/bfbc2.cpp
  plugins/bfheroes/bfheroes.cpp
  plugins/blacklight/blacklight.cpp
  plugins/borderlands/borderlands.cpp
  plugins/borderlands2/borderlands2.cpp
  plugins/breach/breach.cpp
  plugins/cod2/cod2.cpp
  plugins/cod4/cod4.cpp
  plugins/cod5/cod5.cpp
  plugins/codmw2/codmw2.cpp
  plugins/codmw2so/codmw2so.cpp
  plugins/cs/cs.cpp
  plugins/dys/dys.cpp
  plugins/etqw/etqw.cpp
  plugins/ffxiv/ffxiv.cpp
  plugins/gmod/gmod.cpp
  plugins/gtaiv/gtaiv.cpp
  plugins/gtasa/gtasa.cpp
  plugins/gtav/gtav.cpp
  plugins/gw/gw.cpp
  plugins/insurgency/insurgency.cpp
  plugins/jc2/jc2.cpp
  plugins/link/link-posix.cpp
  plugins/link/link.cpp
  plugins/lol/lol.cpp
  plugins/lotro/lotro.cpp
  plugins/mumble_positional_audio_main.h
  plugins/ql/ql.cpp
  plugins/rl/rl.cpp
  plugins/se/se.cpp
  plugins/sr/sr.cpp
  plugins/testPlugin/CMakeLists.txt
  plugins/ut2004/ut2004.cpp
  plugins/ut3/ut3.cpp
  plugins/ut99/ut99.cpp
  plugins/wolfet/wolfet.cpp
  plugins/wow/wow.cpp
  plugins/wow_x64/wow_x64.cpp
Labels: build

#5131 FIX(server): Value queried but not used in DB insertion
  src/murmur/ServerDB.cpp
Labels: backport-needed, bug, server

#5132 FIX(positional-audio): Update Source Engine plugin to work with L4D2 2.2.1.3
  plugins/se/engine.h
Labels: client, positional audio

#5133 Backport "FIX(server): Value queried but not used in DB insertion (#5131)" to 1.4.x
  src/murmur/ServerDB.cpp
Labels: backport

#5130 FIX(server): Missing lock in Ice-call setACL
  src/murmur/MurmurIce.cpp
Labels: backport-needed, bug, server

#5136 Backport "FIX(server): Missing lock in Ice-call setACL (#5130)" to 1.4.x
  src/murmur/MurmurIce.cpp
Labels: backport

#5138 Backport positional audio plugins updates
  plugins/ProcessLinux.cpp
  plugins/amongus/structs.h
  plugins/se/engine.h
Labels: backport, client, positional audio

#5135 FIX(server): Also INSERT queried value
  src/murmur/ServerDB.cpp
Labels: bug, server

#5142 Backport "FIX(server): Also INSERT queried value"
  src/murmur/ServerDB.cpp
Labels: backport

#5144 DOCS: Add note to Mumble.proto
  src/Mumble.proto
Labels: documentation

#5141 FEAT(client,ui): Change tooltip of mute & deaf-buttons depending on their state
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/MainWindow.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, feature-request, ui

#5147 FEAT(client): Allow magnet-URIs for links
  src/mumble/Log.cpp
Labels: client, feature-request

#5127 FEAT(client): Introduce Positional Audio Viewer, replacement for MumblePAHelper
  src/mumble/CMakeLists.txt
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/MainWindow.ui
  src/mumble/PositionalAudioViewer.cpp
  src/mumble/PositionalAudioViewer.h
  src/mumble/PositionalAudioViewer.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, feature-request, positional audio

#5149 FIX(client): Duplicate name in Log.ui
  src/mumble/Log.ui
Labels: bug, build, client

#5122 Translations update from Weblate
  src/mumble/mumble_cs.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation
