Repository mumble-voip/mumble, pull requests merged in 2021-07, with the labels that each got.

#5155 REFAC(positional-audio): Port GTA5 to new Plugin API
  plugins/gtav/CMakeLists.txt
  plugins/gtav/Game.cpp
  plugins/gtav/Game.h
  plugins/gtav/gtav.cpp
Labels: positional audio

#5161 FIX(client): Potential deadlocks in plugins
  plugins/MumbleAPI_v_1_0_x.h
  plugins/PluginComponents_v_1_0_x.h
  src/mumble/API.h
  src/mumble/API_v_1_0_x.cpp
Labels: client

#5162 Backport "FEAT(positional-audio): Update & port GTA5 to new Plugin API"
  plugins/gtav/CMakeLists.txt
  plugins/gtav/Game.cpp
  plugins/gtav/Game.h
  plugins/gtav/gtav.cpp
Labels: backport

#5163 Backport "FIX(client): Potential deadlocks in plugins (#5161)" to 1.4.x
  plugins/MumbleAPI_v_1_0_x.h
  plugins/PluginComponents_v_1_0_x.h
  src/mumble/API.h
  src/mumble/API_v_1_0_x.cpp
Labels: backport

#5164 FEAT(client): Drop the version from window title
  src/mumble/MainWindow.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: accessibility, client, feature-request

#5165 BUILD(cmake): Detect ARM64 on macOS
  cmake/TargetArch.cmake
Labels: build, macOS

#5152 FIX(client): Issues when updating installed plugins
  src/mumble/PluginInstaller.cpp
  src/mumble/PluginInstaller.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport-needed, bug, client

#5167 Backport "FIX(client): Issues when updating installed plugins"
  src/mumble/PluginInstaller.cpp
  src/mumble/PluginInstaller.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport

#5159 FIX(client): Remove unnecessary wait for mutex
  src/mumble/JackAudio.cpp
  src/mumble/JackAudio.h
  src/mumble/PAAudio.cpp
  src/mumble/PAAudio.h
  src/mumble/PipeWire.cpp
  src/mumble/PipeWire.h
  src/mumble/PulseAudio.cpp
  src/mumble/PulseAudio.h
Labels: bug, client

#5168 Backport "FIX(client): Remove unnecessary wait for mutex (#5159)" to 1.4.x
  src/mumble/JackAudio.cpp
  src/mumble/JackAudio.h
  src/mumble/PAAudio.cpp
  src/mumble/PAAudio.h
  src/mumble/PipeWire.cpp
  src/mumble/PipeWire.h
  src/mumble/PulseAudio.cpp
  src/mumble/PulseAudio.h
Labels: backport

#5172 FIX(server): Tray icon not shown on Windows
  src/murmur/CMakeLists.txt
Labels: bug, server

#5173 Backport "FIX(server): Tray icon not shown on Windows (#5172)" to 1.4.x
  src/murmur/CMakeLists.txt
Labels: backport

#5176 FIX(client): Plugin updater keeping plugin locked
  src/mumble/PluginUpdater.cpp
Labels: bug, client

#5177 Backport "MAINT(docker): added frequently used sql drivers (#5175)" to 1.4.x
  Dockerfile
Labels: backport

#5179 Backport "FIX(client): Plugin updater keeping plugin locked (#5176)" to 1.4.x
  src/mumble/PluginUpdater.cpp
Labels: backport

#5183 FIX(client, audio): PulseAudio not initializing
  src/mumble/PulseAudio.cpp
  src/mumble/PulseAudio.h
Labels: audio, bug, client

#5184 Backport "FIX(client, audio): PulseAudio not initializing (#5183)" to 1.4.x
  src/mumble/PulseAudio.cpp
  src/mumble/PulseAudio.h
Labels: backport

#5185 FIX(positional-audio): Update Among Us plugin to work with v2021.6.30s
  plugins/amongus/structs.h
Labels: client, positional audio

#5186 FIX(positional-audio): Update Source Engine plugin to work with L4D2 2.2.2.0
  plugins/se/client.h
Labels: client, positional audio

#5189 Backport "FIX(positional-audio): Update Among Us plugin to work with v2021.6.30s (#5185)" to 1.4.x
  plugins/amongus/structs.h
Labels: backport

#5190 Backport "FIX(positional-audio): Update Source Engine plugin to work with L4D2 2.2.2.0 (#5186)" to 1.4.x
  plugins/se/client.h
Labels: backport

#5191 CI(azure): Don't package AppImage
  .ci/azure-pipelines/steps_linux.yml
Labels: ci

#5169 BUILD(installer): Add file assoc. for plugin-files
  installer/ClientInstaller.cs
Labels: installer

#5192 Backport "BUILD(installer): Add file assoc. for plugin-files (#5169)" to 1.4.x
  installer/ClientInstaller.cs
Labels: backport

#5188 FIX(client): Potential access of invalid object
  src/mumble/API.h
  src/mumble/API_v_1_0_x.cpp
Labels: bug, client

#5195 Backport "CI(azure): Don't package AppImage (#5191)" to 1.4.x
  .ci/azure-pipelines/steps_linux.yml
Labels: backport

#5193 Backport "FIX(client): Potential access of invalid object (#5188)" to 1.4.x
  src/mumble/API.h
  src/mumble/API_v_1_0_x.cpp
Labels: backport

#5200 Backport "MAINT: Make changelog script work with backports (#5199)" to 1.4.x
  scripts/generateChangelog.py
Labels: backport

#5156 Translations update from Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#5202 TRANSLATION: Backport translations
  src/mumble/mumble_cs.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#5178 FIX(client): Migrate Windows shortcuts from versions older than 1.4.0 properly
  src/mumble/GlobalShortcut_win.cpp
  src/mumble/GlobalShortcut_win.h
  src/mumble/main.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, windows

#5205 Backport "FIX(client): Migrate Windows shortcuts from versions older than 1.4.0 properly"
  src/mumble/GlobalShortcut_win.cpp
  src/mumble/GlobalShortcut_win.h
  src/mumble/main.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport

#5211 CI: Update to latest vcpkg environment
  .appveyor.yml
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
Labels: ci

#5209 FIX(server): Always bind to both IPv6 and IPv4 by default
  src/murmur/Meta.cpp
  src/murmur/Server.cpp
  src/murmur/Server.h
Labels: bug, server

#5210 CI: Update to latest vcpkg environment
  .appveyor.yml
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
Labels: ci

#5212 Backport "FIX(server): Always bind to both IPv6 and IPv4 by default (#5209)" to 1.4.x
  src/murmur/Meta.cpp
  src/murmur/Server.cpp
  src/murmur/Server.h
Labels: backport
