Repository mumble-voip/mumble, pull requests merged in 2021-11, with the labels that each got.

#5294 FIX(client): Sort users case-insensitively
  src/User.cpp
Labels: client, ui, bug

#5295 Backport "FIX(client): Sort users case-insensitively (#5294)" to 1.4.x
  src/User.cpp
Labels: backport

#5297 CHANGE(client): Max. value for silent user setting
  src/mumble/LookConfig.ui
Labels: client

#5299 TEST(client): Add plugin to test deadlock prevention
  plugins/CMakeLists.txt
  plugins/deadLockPlugin/CMakeLists.txt
  plugins/deadLockPlugin/deadLockPlugin.cpp
Labels: client, test

#5305 BUILD(client): Fix compile errors without manual plugin
  src/mumble/PluginConfig.cpp
  src/mumble/PluginManager.cpp
  src/mumble/ServerHandler.cpp
Labels: build, backport-needed

#5306 Backport "BUILD(client): Fix compile errors without manual plugin"
  src/mumble/PluginConfig.cpp
  src/mumble/PluginManager.cpp
  src/mumble/ServerHandler.cpp
Labels: backport

#5298 FEAT(server): Add option to disallow recording
  scripts/murmur.ini
  src/Mumble.proto
  src/mumble/Global.cpp
  src/mumble/Global.h
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/MainWindow.ui
  src/mumble/Messages.cpp
  src/mumble/VoiceRecorderDialog.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
  src/murmur/Messages.cpp
  src/murmur/Meta.cpp
  src/murmur/Meta.h
  src/murmur/Server.cpp
  src/murmur/Server.h
Labels: client, server, feature-request, backport-needed

#5309 Backport "FIX(client): Crash when starting recording"
  src/mumble/VoiceRecorderDialog.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport

#5308 FIX(server, ice): Missing locks in ICE functions
  src/murmur/MurmurIce.cpp
Labels: server, ice, backport-needed, bug

#5280 FIX(server,client): Validate/use the correct certifiacte from a chain
  src/Connection.cpp
  src/Connection.h
  src/mumble/ServerHandler.cpp
  src/murmur/Server.cpp
Labels: backport-needed, bug

#5307 FIX(client): Disable broken shortcuts on Wayland
  src/EnvUtils.cpp
  src/EnvUtils.h
  src/mumble/GlobalShortcut.cpp
  src/mumble/GlobalShortcut.ui
  src/mumble/GlobalShortcut_unix.cpp
  src/mumble/Settings.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, GlobalShortcuts

#5315 Backport "FIX(client): Disable broken shortcuts on Wayland"
  src/EnvUtils.cpp
  src/EnvUtils.h
  src/mumble/GlobalShortcut.cpp
  src/mumble/GlobalShortcut.ui
  src/mumble/GlobalShortcut_unix.cpp
  src/mumble/Settings.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport

#5323 BUILD(client): Add missing ifdef guards
  src/mumble/GlobalShortcut_win.cpp
Labels: build, backport-needed

#5326 Backport "BUILD(client): Add missing ifdef guards (#5323)" to 1.4.x
  src/mumble/GlobalShortcut_win.cpp
Labels: backport

#5325 FIX(client): Duplicate plugin entries
  src/mumble/PluginManager.cpp
Labels: client, backport-needed, bug

#5327 Backport "FIX(client): Duplicate plugin entries (#5325)" to 1.4.x
  src/mumble/PluginManager.cpp
Labels: backport

#5311 Backport "FIX(server,client): Validate/use the correct certifiacte from a peers chain (#5280)" to 1.4.x
  src/Connection.cpp
  src/Connection.h
  src/mumble/ServerHandler.cpp
  src/murmur/Server.cpp
Labels: backport

#5310 Backport "FIX(server, ice): Missing locks in ICE functions (#5308)" to 1.4.x
  src/murmur/MurmurIce.cpp
Labels: backport

#5333 FIX(client): Error if API call can't work due to server
  plugins/MumbleAPI_v_1_0_x.h
  plugins/PluginComponents_v_1_0_x.h
  src/mumble/API_v_1_0_x.cpp
Labels: client, backport-needed, bug

#5336 DOCS(api): Fix typo
  docs/dev/plugins/PluginAPI.md
Labels: documentation

#5337 Backport "FIX(client): Error if API call can't work due to server (#5333)" to 1.4.x
  plugins/MumbleAPI_v_1_0_x.h
  plugins/PluginComponents_v_1_0_x.h
  src/mumble/API_v_1_0_x.cpp
Labels: backport

#5339 FIX(client): Wrong entry in plugin search path
  src/mumble/PluginManager.cpp
Labels: client, bug

#5342 BUILD: Use build number instead of patch version
  .ci/install-environment_windows.ps1
  CMakeLists.txt
  g15helper/g15helper.rc.in
  installer/ClientInstaller.cs
  installer/ServerInstaller.cs
  overlay/mumble_ol.rc.in
  overlay/overlay_exe/overlay_exe.rc.in
  overlay_winx64/mumble_ol.rc.in
  overlay_winx64/overlay_exe_winx64/overlay_exe.rc.in
  src/mumble/mumble.rc.in
  src/mumble/mumble_dll.rc.in
  src/murmur/murmur.rc.in
Labels: build, backport-needed

#5343 Backport "BUILD: Use build number instead of patch version"
  .ci/install-environment_windows.ps1
  CMakeLists.txt
  cmake/fetch_dependencies.cmake
  g15helper/g15helper.rc.in
  installer/ClientInstaller.cs
  installer/ServerInstaller.cs
  overlay/mumble_ol.rc.in
  overlay/overlay_exe/overlay_exe.rc.in
  overlay_winx64/mumble_ol.rc.in
  overlay_winx64/overlay_exe_winx64/overlay_exe.rc.in
  src/mumble/mumble.rc.in
  src/mumble/mumble_dll.rc.in
  src/murmur/murmur.rc.in
Labels: backport

#5340 Backport "FIX(client): Wrong entry in plugin search path (#5339)" to 1.4.x
  src/mumble/PluginManager.cpp
Labels: backport
