Repository mumble-voip/mumble, pull requests merged in 2022-10, with the labels that each got.

#5916 FIX(client): Fixes link context menu creation for channels
  src/mumble/Log.cpp
  src/mumble/MainWindow.cpp
Labels: client, backport-needed, bug

#5918 FIX(server): Explicitly set parsed timestamps to UTC for rememberchannelduration
  src/murmur/ServerDB.cpp
Labels: server, backport-needed, bug

#5927 FIX(client, ui): remove gaps within chat
  src/mumble/Log.cpp
Labels: client, ui, bug

#5928 CI(github-actions): Update Ubuntu runners
  .github/actions/install-dependencies/install_ubuntu_shared_64bit.sh
  .github/workflows/build.yml
Labels: backport-needed, ci

#5917 FIX(client): Fix target and permission selection in updateMenuPermissions
  src/mumble/MainWindow.cpp
Labels: client, backport-needed, bug
