Repository mumble-voip/mumble, pull requests merged in 2022-12, with the labels that each got.

#5991 REFAC(server): Improve readability of Group::isMember
  src/ACL.cpp
  src/Group.cpp
  src/Group.h
  src/murmur/Server.cpp
Labels: server

#5978 Translations update from Hosted Weblate
  src/mumble/mumble_ca.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#5992 BUILD(cmake): only assert install paths are relative when packaging
  cmake/install-paths.cmake
Labels: build

#5995 FIX(client): Prevent loading unwanted Opus version
  src/mumble/OpusCodec.cpp
Labels: client

#6000 BUILD(cmake): Cross-compile overlay on M1 macs
  CMakeLists.txt
Labels: overlay, build
