Repository mumble-voip/mumble, pull requests merged in 2022-08, with the labels that each got.

#5769 FIX(server): Update suppress state on ACL change
  src/murmur/Server.cpp
Labels: server, backport-needed, bug

#5772 FIX(ui): User and channel status icons take display scaling into account
  src/mumble/UserView.cpp
  src/mumble/UserView.h
Labels: client, ui, backport-needed, bug

#5771 FIX(theme): Adapt Qt behavior change regarding padding in QMenu
  src/mumble/MainWindow.ui
  themes/Default/Dark.qss
  themes/Default/Lite.qss
  themes/Default/source/Imports/Base Theme.scss
Labels: client, ui, theme, bug

#5773 FIX(client): Prefer selected tree item for context menu creation
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
Labels: client, backport-needed, bug

#5777 FIX/FEAT(client, ui): Minimal view improvements
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, ui, feature-request, backport-needed, bug

#5778 Backport "Merge PR #5773: FIX(client): Prefer selected tree item for context menu creation" to 1.4.x
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
Labels: backport

#5780 Backport "Merge PR #5769: FIX(server): Update suppress state on ACL change" to 1.4.x
  src/murmur/Server.cpp
Labels: backport

#5782 Backport "FIX(client,ui): Show friendlier text when displaying notifications" to 1.4.x
  src/mumble/Log.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport

#5779 Backport "Merge PR #5772: FIX(ui): User and channel status icons take display scaling into account" to 1.4.x
  src/mumble/UserView.cpp
  src/mumble/UserView.h
Labels: backport

#5781 Backport "Merge PR #5768: FIX(client, ui): Don't display unsupported ACL" to 1.4.x
  src/mumble/ACLEditor.cpp
Labels: backport

#5783 Backport "Merge PR #5750: FIX(client): properly verify certificates when SRV records are used" to 1.4.x
  src/ServerResolver.cpp
  src/mumble/ServerHandler.cpp
  src/mumble/ServerHandler.h
Labels: backport

#5784 Backport "Merge PR #5739: FIX(client): Register simultaneous mouse button presses separately" to 1.4.x
  src/mumble/GlobalShortcut_win.cpp
Labels: backport

#5785 Backport "Merge PR #5688: CHANGE(client): Don't hard block shortcuts on Wayland" to 1.4.x
  src/mumble/GlobalShortcut.cpp
  src/mumble/GlobalShortcut.ui
  src/mumble/GlobalShortcut_unix.cpp
  src/mumble/GlobalShortcut_unix.h
  src/mumble/Settings.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport

#5788 TRANSLATION: Fix typo
  src/mumble/MainWindow.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: translation

#5786 Backport "FIX(client, ui): Minimal view not always working" to 1.4.x
  src/mumble/MainWindow.cpp
Labels: backport

#5766 Translations update from Hosted Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#5790 TRANSLATION: Backport translations
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation, backport

#5794 FIX(ui): Remove duplicate entry for "What's this?" in UserModel
  src/mumble/UserModel.cpp
Labels: client, ui, bug

#5795 Backport "Merge PR #5794: FIX(ui): Remove duplicate entry for "What's this?" in UserModel" to 1.4.x
  src/mumble/UserModel.cpp
Labels: backport

#5796 Backport "CI: Use new build-number script" to 1.4.x
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/build_windows.bat
Labels: backport

#5797 BUILD: Disable warnings-as-errors
  CMakeLists.txt
  docs/dev/build-instructions/cmake_options.md
Labels: build

#5803 Backport "MAINT: Fix mumble-build-number.py script"
  scripts/mumble-build-number.py
Labels: backport

#5814 MAINT: Extend changelog script
  scripts/generateChangelog.py
Labels: backport-needed

#5821 FIX(client): Broken link targets with percent signs
  src/mumble/Markdown.cpp
Labels: client, backport-needed, bug

#5823 FIX(theme): update fallback path for skins
  src/mumble/Themes.cpp
Labels: client, theme, backport-needed, bug

#5833 FIX(client, ui): Make hiding UI elements persistent again
  src/mumble/MainWindow.cpp
Labels: client, ui, backport-needed, bug

#5822 FIX(client): Use correct font size for scaling status icons
  src/mumble/UserView.cpp
  src/mumble/UserView.h
Labels: client, ui, backport-needed, bug

#5834 FIX(client, ui): Don't allow manual toggling of minimal view note
  src/mumble/MainWindow.cpp
Labels: client, ui, backport-needed, bug

#5835 BUILD(appstream): Include release date
  CMakeLists.txt
  scripts/info.mumble.Mumble.appdata.xml.in
Labels: release-management, backport-needed

#5820 FIX(ui): resolve text/icon scaling issues
  src/mumble/Log.cpp
Labels: client, backport-needed, bug

#5843 BUILD(build): Fix -mbig-obj test
  cmake/compiler.cmake
Labels: build

#5846 BUILD: Always build Tracy as static library
  src/CMakeLists.txt
Labels: build, backport-needed
