Repository mumble-voip/mumble, pull requests merged in 2022-11, with the labels that each got.

#5952 BUILD(cmake): the "optimize" option
  cmake/compiler.cmake
Labels: build

#5953 BUILD(cmake): Fix build without RNNoise
  src/mumble/JSONSerialization.cpp
Labels: build

#5957 BUILD(cmake): Fix syntax error
  cmake/qt-utils.cmake
Labels: build

#5880 Translations update from Hosted Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#5949 FIX(overlay): Implement library search list for dlsym(), add "libc.so.6" to it
  overlay_gl/init_unix.c
Labels: overlay, linux

#5923 Channel filter improvements
  src/Channel.cpp
  src/Channel.h
  src/mumble/CMakeLists.txt
  src/mumble/ChannelFilterMode.h
  src/mumble/Database.cpp
  src/mumble/Database.h
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/MainWindow.ui
  src/mumble/Messages.cpp
  src/mumble/UserModel.cpp
  src/mumble/UserModel.h
  src/mumble/UserView.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
  themes/Default/pin.svg
  themes/DefaultTheme.qrc
Labels: client, ui, feature-request

#5948 FEAT(server): Flag bot connections, so user count does not get inflated by them
  src/Mumble.proto
  src/murmur/ClientType.h
  src/murmur/Messages.cpp
  src/murmur/Server.cpp
  src/murmur/Server.h
  src/murmur/ServerUser.cpp
  src/murmur/ServerUser.h
Labels: server, feature-request

#5925 Priority speakers and temporary channels
  src/murmur/Messages.cpp
  src/murmur/Server.cpp
Labels: server, backport-needed, bug

#5980 TRANSLATION: Update translation files
  src/mumble/mumble_hi.ts
Labels: translation

#5967 BUILD(overlay): build overlay on Linux and FreeBSD without client flag
  CMakeLists.txt
  auxiliary_files/CMakeLists.txt
  docs/dev/build-instructions/cmake_options.md
  src/CMakeLists.txt
Labels: overlay, build
