Repository mumble-voip/mumble, pull requests merged in 2022-02, with the labels that each got.

#5550 BUILD(client,server): Include time.h instead of sys/time.h
  src/Timer.cpp
Labels: build, backport-needed

#5530 FIX(client): Fix PipeWire not being usable in Flatpaks
  src/mumble/PipeWire.cpp
Labels: release-management, audio, backport-needed, bug

#5528 Backport "FIX(installer): Re-add URL protocol registration registry keys on install (#5521)" to 1.4.x
  installer/ClientInstaller.cs
Labels: backport

#5514 CI: scripts/runClangFormat.sh: Use git-ls-files(1)
  scripts/runClangFormat.sh
Labels: ci

#5499 Backport "FIX(client): Improve appstream metadata (#5468)" to 1.4.x
  scripts/info.mumble.Mumble.appdata.xml.in
  scripts/info.mumble.Mumble.desktop
  scripts/org.mumble_voip.mumble.appdata.xml
  src/CMakeLists.txt
Labels: backport

#5490 DOCS: Add FindPythonInterpreter error to common build errors
  docs/dev/build-instructions/common_build_errors.md
Labels: documentation

#5470 CHANGE(ui): Update ear.svg to fit with other icons
  themes/Default/ear.svg
Labels: client, ui

#5464 Backport "BUILD(client): RNNoise: Support linking against the system library"
  docs/dev/build-instructions/cmake_options.md
  src/mumble/CMakeLists.txt
Labels: backport

#5457 Backport "MAINT(macOS): Add client entitlements plist, for hardened runtime to work (#5093)" to 1.4.x
  src/mumble/mumble.entitlements.plist
Labels: backport

#5456 Backport "FIX(server): Add missing line breaks to --help output (#5443)" to 1.4.x
  src/murmur/main.cpp
Labels: backport

#5455 CHANGE(ui): Make lock icons fit with other icons
  themes/Default/lock_locked.svg
  themes/Default/lock_unlocked.svg
Labels: client, ui, backport-needed

#5551 CI(appveyor): Enable shortcut elevation for signed builds
  .appveyor.yml
  .ci/build_windows.bat
Labels: backport-needed, ci

#5540 DOCS: Fix typos
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
  cmake/compiler.cmake
  src/ACL.cpp
  src/licenses.h
  src/mumble/API.h
  src/mumble/AudioInput.cpp
  src/mumble/AudioInput.h
  src/mumble/AudioOutput.cpp
  src/mumble/AudioOutput.h
  src/mumble/AudioOutputSample.cpp
  src/mumble/CMakeLists.txt
  src/mumble/ConnectDialog.cpp
  src/mumble/ConnectDialog.h
  src/mumble/DBus.h
  src/mumble/LegacyPlugin.cpp
  src/mumble/ListenerLocalVolumeDialog.h
  src/mumble/Log.cpp
  src/mumble/MainWindow.cpp
  src/mumble/ManualPlugin.h
  src/mumble/Markdown.cpp
  src/mumble/Messages.cpp
  src/mumble/MumbleApplication.cpp
  src/mumble/OverlayConfig.h
  src/mumble/Overlay_macx.mm
  src/mumble/Overlay_win.cpp
  src/mumble/Plugin.cpp
  src/mumble/Plugin.h
  src/mumble/PluginInstaller.h
  src/mumble/PluginManager.cpp
  src/mumble/PluginManager.h
  src/mumble/PluginManifest.cpp
  src/mumble/PluginUpdater.h
  src/mumble/PulseAudio.cpp
  src/mumble/SearchDialog.cpp
  src/mumble/Settings.cpp
  src/mumble/ThemeInfo.h
  src/mumble/Themes.cpp
  src/mumble/Themes.h
  src/mumble/UserEdit.h
  src/mumble/UserListModel.cpp
  src/mumble/VoiceRecorder.h
  src/mumble/VoiceRecorderDialog.cpp
  src/mumble/WASAPI.cpp
  src/mumble/WebFetch.h
  src/mumble/WinGUIDs.cpp
  src/mumble/XMLTools.h
  src/mumble/XboxInput.h
  src/mumble/main.cpp
  src/mumble/os_macx.mm
  src/mumble/qttranslations/translations.conf
  src/mumble/widgets/RichTextItemDelegate.h
Labels: documentation

#5533 DOCS: Add missing build dependency
  docs/dev/build-instructions/build_linux.md
Labels: documentation

#5509 BUILD(client): Remove USE_OPUS define, make Opus a hard requirement
  src/mumble/Audio.cpp
  src/mumble/AudioInput.cpp
  src/mumble/AudioOutputSpeech.cpp
  src/mumble/CMakeLists.txt
  src/mumble/Global.cpp
  src/mumble/MainWindow.cpp
  src/mumble/Messages.cpp
  src/mumble/ServerHandler.cpp
Labels: build

#5502 BUILD(client): overlay_gl: Detect OpenBSD
  CMakeLists.txt
  overlay_gl/CMakeLists.txt
Labels: build

#5557 Backport "MAINT(manpages): Replace `murmur` with `mumble-server`" to 1.4.x
  man/mumble-server-user-wrapper.1
  man/mumble-server.1
  scripts/mumble-server-user-wrapper
  src/murmur/CMakeLists.txt
Labels: backport

#5564 FIX(client): Percent encoded links not clickable
  src/mumble/Markdown.cpp
Labels: client, backport-needed, bug

#5566 FIX(client,ui): PFS information being incorrect
  scripts/generate-cipherinfo.py
  src/CMakeLists.txt
  src/SSLCipherInfo.cpp
  src/SSLCipherInfo.h
  src/SSLCipherInfoTable.h
  src/mumble/MainWindow.cpp
  src/mumble/ServerHandler.cpp
  src/mumble/ServerHandler.h
  src/mumble/ServerInformation.cpp
  src/mumble/ServerInformation.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, backport-needed, bug

#5587 BUILD(positional-audio): Fix missing <memory> include
  plugins/gtav/gtav.cpp
Labels: build, backport-needed
