Repository mumble-voip/mumble, pull requests merged in 2022-06, with the labels that each got.

#5715 CHANGE(cli): Fix CLI help typo ‘fir’ -> ‘dir’ -> ‘directory’
  src/mumble/main.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client

#5704 FEAT/REFAC(positional-audio): Rewrite GTAV plugin, define "procid_t" to "uint64_t"
  plugins/HostLinux.h
  plugins/HostWindows.h
  plugins/ProcessBase.cpp
  plugins/ProcessBase.h
  plugins/amongus/Game.cpp
  plugins/amongus/Game.h
  plugins/gtav/Game.cpp
  plugins/gtav/Game.h
  plugins/gtav/gtav.cpp
  plugins/gtav/structs.h
  plugins/mumble_legacy_plugin.h
Labels: client, positional audio

#5720 Backport "FEAT/REFAC(positional-audio): Rewrite GTAV plugin, define "procid_t" to "uint64_t"" to 1.4.x
  plugins/HostLinux.h
  plugins/HostWindows.h
  plugins/ProcessBase.cpp
  plugins/ProcessBase.h
  plugins/amongus/Game.cpp
  plugins/amongus/Game.h
  plugins/gtav/Game.cpp
  plugins/gtav/Game.h
  plugins/gtav/gtav.cpp
  plugins/gtav/structs.h
  plugins/mumble_legacy_plugin.h
Labels: backport

#5716 DOCS(winbuild): Add troubleshooting for missing MFC dependency
  docs/dev/build-instructions/build_static.md
Labels: documentation
