Repository mumble-voip/mumble, pull requests merged in 2022-05, with the labels that each got.

#5640 FIX(positional-audio): Fix Quake Live plugin
  plugins/ql/ql.cpp
Labels: backport-needed

#5641 CI: Also fetch build number token on GA
  .github/workflows/build.sh
  .github/workflows/build.yml
  .github/workflows/pr-checks.yml
  .github/workflows/set_environment_variables.sh
Labels: ci

#5644 Backport "CI: Also fetch build number token on GA"
  .github/workflows/build.sh
  .github/workflows/build.yml
  .github/workflows/pr-checks.yml
  .github/workflows/set_environment_variables.sh
  scripts/mumble-build-number.py
Labels: backport

#5601 Translations update from Hosted Weblate
  src/mumble/mumble_ca.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#5646 FIX(server): Improve rememberchannelduration compare logic
  src/murmur/ServerDB.cpp
  src/murmur/ServerDB.h
  src/murmur/main.cpp
Labels: server, backport-needed, bug

#5648 FIX(client): Prevent endless loop when disconnecting PipeWire stream
  src/mumble/PipeWire.cpp
Labels: client, audio, backport-needed, bug

#5649 CI: Add dispatch for new releases
  .github/workflows/release_dispatch.yml
Labels: ci

#5651 Backport "Merge PR #5648: FIX(client): Prevent endless loop when disconnecting PipeWire stream" to 1.4.x
  src/mumble/PipeWire.cpp
Labels: backport

#5652 Backport "Merge PR #5646: FIX(server): Improve rememberchannelduration compare logic" to 1.4.x
  src/murmur/ServerDB.cpp
  src/murmur/ServerDB.h
  src/murmur/main.cpp
Labels: backport

#5653 Backport "Merge PR #5640: FIX(positional-audio): Fix Quake Live plugin" to 1.4.x
  plugins/ql/ql.cpp
Labels: backport

#5654 Backport "Merge PR #5612: FIX(positional-audio): Update Among Us plugin to work with v2022.3.29s (1864)" to 1.4.x
  plugins/amongus/structs.h
Labels: backport

#5655 Backport "Merge PR #5587: BUILD(positional-audio): Fix missing <memory> include" to 1.4.x
  plugins/gtav/gtav.cpp
Labels: backport

#5656 Backport "Merge PR #5566: FIX(client,ui): PFS information being incorrect" to 1.4.x
  scripts/generate-cipherinfo.py
  src/CMakeLists.txt
  src/SSLCipherInfo.cpp
  src/SSLCipherInfo.h
  src/SSLCipherInfoTable.h
  src/mumble/MainWindow.cpp
  src/mumble/ServerHandler.cpp
  src/mumble/ServerHandler.h
  src/mumble/ServerInformation.cpp
  src/mumble/ServerInformation.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport

#5657 Backport "Merge PR #5564: FIX(client): Percent encoded links not clickable" to 1.4.x
  src/mumble/Markdown.cpp
Labels: backport

#5658 Backport "Merge PR #5554: FIX(client): Context and identity not getting cleared" to 1.4.x
  src/mumble/PluginManager.cpp
Labels: backport

#5660 Backport "Merge PR #5551: CI(appveyor): Enable shortcut elevation for signed builds" to 1.4.x
  .appveyor.yml
  .ci/build_windows.bat
Labels: backport

#5661 Backport "Merge PR #5550: BUILD(client,server): Include time.h instead of sys/time.h" to 1.4.x
  src/Timer.cpp
Labels: backport

#5609 BUILD(client): Fix various issues
  src/mumble/Markdown.cpp
  src/mumble/PluginManifest.cpp
  src/mumble/QtWidgetUtils.cpp
  src/mumble/QtWidgetUtils.h
  src/mumble/SearchDialog.cpp
Labels: client, build, backport-needed

#5662 Backport "Merge PR #5536: FIX(client): Icon not used on Plasma Wayland session" to 1.4.x
  src/mumble/main.cpp
Labels: backport

#5663 Backport "Merge PR #5530: FIX(client): Fix PipeWire not being usable in Flatpaks" to 1.4.x
  src/mumble/PipeWire.cpp
Labels: backport

#5664 Backport "Merge PR #5503: BUILD(client): CELT: Require version 0.7.x when using the system library" to 1.4.x
  src/mumble/CMakeLists.txt
Labels: backport

#5650 Translations update from Hosted Weblate
  src/mumble/mumble_ru.ts
Labels: translation

#5665 Backport "Merge PR #5428: MAINT: Add script to sign macOS binaries and packages" to 1.4.x
  scripts/sign_macOS.py
Labels: backport

#5667 BUILD(macos): Fix plugins not getting bundled
  macx/scripts/osxdist.py
Labels: release-management, backport-needed

#5666 Backport "Merge PR #5609: BUILD(client): Fix various issues" to 1.4.x
  src/mumble/Markdown.cpp
  src/mumble/PluginManifest.cpp
  src/mumble/QtWidgetUtils.cpp
  src/mumble/QtWidgetUtils.h
  src/mumble/SearchDialog.cpp
Labels: backport

#5668 Backport "Merge PR #5667: BUILD(macos): Fix plugins not getting bundled" to 1.4.x
  macx/scripts/osxdist.py
Labels: backport

#5603 DOCS(build_linux): Added build instructions for Debian, w/ related Ubuntu issues
  docs/dev/build-instructions/build_linux.md
Labels: documentation

#5669 TRANSLATION: Backport translations from master
  src/mumble/mumble_ca.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_TW.ts
Labels: translation, backport

#5671 CI(azure): Switch to using python3 instead of python
  .ci/azure-pipelines/assertNoTranslationChanges.sh
  .ci/azure-pipelines/release_macos.bash
Labels: ci

#5676 MAINT(vcpkg): Install protobuf
  scripts/vcpkg/get_mumble_dependencies.ps1
  scripts/vcpkg/get_mumble_dependencies.sh
Labels: build, backport-needed

#5674 CI: Remove x86 Windows build(s), update build environment(s)
  .appveyor.yml
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
Labels: ci

#5682 CI(macos): Use azure-hosted runner
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
Labels: ci

#5678 Backport "MAINT(vcpkg): Install protobuf" to 1.4.x
  scripts/vcpkg/get_mumble_dependencies.ps1
  scripts/vcpkg/get_mumble_dependencies.sh
Labels: backport

#5679 FIX(positional-audio): Update GTAV plugin to version 1.59.2612
  plugins/gtav/Game.cpp
  plugins/gtav/gtav.cpp
Labels: positional audio, backport-needed

#5677 CHANGE(client): Disable RNNoise by default
  src/mumble/Settings.cpp
  src/tests/TestSettingsJSONSerialization/generate_test_case.py
Labels: client, backport-needed

#5690 CI(macos): Use correct build env on macOS nightly builds
  .ci/azure-pipelines/main.yml
Labels: ci

#5697 DOCS(build_linux): Added dependency install instructions for OpenSUSE Tumbleweed
  docs/dev/build-instructions/build_linux.md
Labels: documentation

#5686 MAINT(build): Update SHA512 hash in zeroc-ice-mumble portfile
  helpers/vcpkg/ports/zeroc-ice-mumble/portfile.cmake
Labels: build

#5698 BUILD(windows): Workaround for Microsoft STL linker compatibility breakage
  cmake/compiler.cmake
Labels: build

#5689 Backport "Merge PR #5677: CHANGE(client): Disable RNNoise by default" to 1.4.x
  src/mumble/Settings.cpp
Labels: backport

#5703 BUILD: Fix missing <cstdint> include
  plugins/Module.h
Labels: build

#5705 Backport "BUILD: Fix missing <cstdint> include" to 1.4.x
  plugins/Module.h
Labels: backport
