Repository mumble-voip/mumble, pull requests merged in 2022-07, with the labels that each got.

#5739 FIX(client): Register simultaneous mouse button presses separately
  src/mumble/GlobalShortcut_win.cpp
Labels: client, windows, backport-needed, GlobalShortcuts

#5750 FIX(client): properly verify certificates when SRV records are used
  src/ServerResolver.cpp
  src/mumble/ServerHandler.cpp
  src/mumble/ServerHandler.h
Labels: client, backport-needed, bug

#5751 FIX(server): Don't silently ignore errors in INI
  src/murmur/Meta.cpp
Labels: server, bug

#5752 BUILD(cmake, overlay): Include missing CMake module
  overlay_gl/CMakeLists.txt
Labels: build, backport-needed

#5753 DOCS: Document missing option in murmur.ini
  scripts/murmur.ini
Labels: documentation, backport-needed

#5755 Backport "BUILD(cmake, overlay): Include missing CMake module" to 1.4.x
  overlay_gl/CMakeLists.txt
Labels: backport

#5754 BUILD(overlay): Remove dead code
  src/mumble/Overlay_macx.mm
Labels: build

#5714 FEAT(client, ui): separate ipv4 and ipv6 in ServerItem tooltip
  src/HostAddress.cpp
  src/HostAddress.h
  src/mumble/ConnectDialog.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, ui, feature-request

#5744 FEAT(client): Add shortcut to send plain text messages
  src/mumble/CustomElements.cpp
  src/mumble/CustomElements.h
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
Labels: client, feature-request

#5757 Backport "DOCS: Document missing option in murmur.ini" to 1.4.x
  scripts/murmur.ini
Labels: backport

#5761 TRANSLATION: Add Slovak (sk) template
  src/mumble/mumble_sk.ts
Labels: translation

#5688 CHANGE(client): Don't hard block shortcuts on Wayland
  src/mumble/GlobalShortcut.cpp
  src/mumble/GlobalShortcut.ui
  src/mumble/GlobalShortcut_unix.cpp
  src/mumble/GlobalShortcut_unix.h
  src/mumble/Settings.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, backport-needed

#5765 FIX(client,ui): Show friendlier text when displaying notifications
  src/mumble/Log.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, ui, bug

#5768 FIX(client, ui): Don't display unsupported ACL
  src/mumble/ACLEditor.cpp
Labels: client, backport-needed, bug

#5767 FIX(server): Don't ignore explicit PermissionQuery
  src/murmur/Server.cpp
  src/murmur/Server.h
Labels: server, bug
