Repository mumble-voip/mumble, pull requests merged in 2022-01, with the labels that each got.

#5399 Backport "CHANGE(client): Remove channel listener persistence"
  src/ChannelListenerManager.cpp
  src/ChannelListenerManager.h
  src/mumble/Database.cpp
  src/mumble/Database.h
  src/mumble/MainWindow.cpp
  src/mumble/Messages.cpp
Labels: backport

#5398 DOCS: Clarify MAINT type in commit guidelines
  COMMIT_GUIDELINES.md
Labels: documentation

#5400 BUILD: Remove concept of an RELEASE_ID
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/release_macos.bash
  .ci/build_windows.bat
  CMakeLists.txt
  docs/dev/build-instructions/README.md
  docs/dev/build-instructions/find_build_number.md
  scripts/mumble-version.py
  src/CMakeLists.txt
  src/Version.h
Labels: build, release-management, backport-needed

#5402 BUILD: Fix build error
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
Labels: build

#5401 Backport "BUILD: Remove concept of an RELEASE_ID (#5400)" to 1.4.x
  .ci/azure-pipelines/build_linux.bash
  .ci/azure-pipelines/build_macos.bash
  .ci/azure-pipelines/release_macos.bash
  .ci/build_windows.bat
  CMakeLists.txt
  scripts/mumble-version.py
  src/CMakeLists.txt
  src/Version.h
Labels: backport

#5406 FEAT(client): Improve handling of IP masks in BanEditor
  src/mumble/BanEditor.cpp
Labels: client, ui, feature-request

#5418 MAINT: Change build-number token for AppVeyor
  .appveyor.yml
Labels: backport-needed

#5416 BUILD(client): Plugin Framework: Fix build on NetBSD and OpenBSD
  src/ProcessResolver.cpp
Labels: build

#5419 Backport "MAINT: Change build-number token for AppVeyor (#5418)" to 1.4.x
  .appveyor.yml
Labels: backport

#5417 BUILD(audiowizard): Fix build with -Dspeechd=OFF -Dwarnings-as-errors=ON
  src/mumble/AudioWizard.cpp
Labels: build

#5423 CI(azure): checkDocs: Generate unified diffs
  .ci/azure-pipelines/checkDocs.bash
Labels: ci

#5431 CI: Update clang-format action
  .github/workflows/pr-checks.yml
Labels: backport-needed

#5433 Backport "CI: Update clang-format action (#5431)" to 1.4.x
  .github/workflows/pr-checks.yml
Labels: backport

#5435 DOCS(docker): Document Docker Compose '--build' switch.
  docs/DockerCompose.md
Labels: documentation

#5442 BUILD: Use GNUInstallDirs to install resources into share
  src/CMakeLists.txt
Labels: build

#5443 FIX(server): Add missing line breaks to --help output
  src/murmur/main.cpp
Labels: server, bug

#5478 BUILD: include libgen.h for files which use basename(3)
  plugins/HostLinux.cpp
  plugins/mumble_positional_audio_linux.h
Labels: build

#5480 BUILD: include poll.h for poll(3) (instead of sys/poll.h)
  src/mumble/ALSAAudio.cpp
Labels: build

#5479 BUILD: Fix -Wunused-function when compiling without rnnoise
  src/mumble/AudioInput.cpp
Labels: build

#5468 Improve appstream metadata
  scripts/info.mumble.Mumble.appdata.xml.in
  scripts/info.mumble.Mumble.desktop
  scripts/org.mumble_voip.mumble.appdata.xml
  src/CMakeLists.txt
Labels: release-management

#5487 BUILD(client): Enable XInput2 support on OpenBSD by default
  docs/dev/build-instructions/cmake_options.md
  src/mumble/CMakeLists.txt
Labels: build

#5486 BUILD: Build tests in package builds by default
  CMakeLists.txt
  docs/dev/build-instructions/cmake_options.md
Labels: build

#5503 BUILD(client): CELT: Require version 0.7.x when using the system library
  src/mumble/CMakeLists.txt
Labels: backport-needed

#5500 DOCS: General intro to Mumble's source code
  README.md
  docs/dev/TheMumbleSourceCode.md
Labels: documentation

#5438 FEAT(client): Industry standard for hold time
  src/mumble/AudioInput.cpp
  src/mumble/AudioInput.h
  src/mumble/Settings.cpp
Labels: client, feature-request

#5521 FIX(installer): Re-add URL protocol registration registry keys on install
  installer/ClientInstaller.cs
Labels: installer, bug

#5532 Update GTAV positional audio plugin to v1.58.2545
  plugins/gtav/Game.cpp
  plugins/gtav/Game.h
  plugins/gtav/gtav.cpp
Labels: client, positional audio, backport-needed

#5536 FIX(client): Icon not used on Plasma Wayland session
  src/mumble/main.cpp
Labels: client, backport-needed, bug
