Repository mumble-voip/mumble, pull requests merged in 2023-12, with the labels that each got.

#6267 FIX(server): Cap receiver ranges at a vol. diff of 5dB
  src/murmur/AudioReceiverBuffer.h
  src/tests/TestAudioReceiverBuffer/TestAudioReceiverBuffer.cpp
Labels: server, backport-needed, bug, auto-backport-to-1.5.x

#6269 Backport "Merge PR #6265: TRANSLATION: Add missing word in audio wizard ui" to 1.5.x
  src/mumble/AudioWizard.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport

#6271 Backport "Merge PR #6268: FIX(plugins): Compilation with new unified header" to 1.5.x
  plugins/MumblePlugin.h
  plugins/deadLockPlugin/deadLockPlugin.cpp
  plugins/testPlugin/testPlugin.cpp
Labels: backport

#6286 MAINT: Fix invalid escape sequences in generateIceWrapper.py
  scripts/generateIceWrapper.py
Labels: backport-needed, auto-backport-to-1.5.x

#6272 Backport "Merge PR #6267: FIX(server): Cap receiver ranges at a vol. diff of 5dB" to 1.5.x
  src/murmur/AudioReceiverBuffer.h
  src/tests/TestAudioReceiverBuffer/TestAudioReceiverBuffer.cpp
Labels: backport

#6287 Backport "Merge PR #6286: MAINT: Fix invalid escape sequences in generateIceWrapper.py" to 1.5.x
  scripts/generateIceWrapper.py
Labels: backport

#6261 FIX(client, Markdown): Code blocks end on three backticks (```) witho…
  src/mumble/Markdown.cpp
Labels: client, backport-needed, bug, auto-backport-to-1.5.x

#6205 DOCS(build): Update Ubuntu package names
  docs/dev/build-instructions/build_linux.md
Labels: documentation

#6293 Backport "Merge PR #6261: FIX(client,markdown): Don't end code-blocks on first backtick" to 1.5.x
  src/mumble/Markdown.cpp
Labels: backport

#6290 FIX(client, ui): Fix log incorrectly scrolling up
  src/mumble/CustomElements.cpp
  src/mumble/CustomElements.h
Labels: client, ui, bug

#6200 FIX(client, theme): Chinese characters not displayed properly (scss modified)
  themes/Default/Dark.qss
  themes/Default/Lite.qss
  themes/Default/source/Imports/Dark Definitions.scss
  themes/Default/source/Imports/Lite Definitions.scss
Labels: client, ui, bug

#6260 FEAT(client): Implemented new Global Shortcuts
  src/mumble/GlobalShortcutTypes.h
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, ui, feature-request

#6292 CHANGE(client): Exclude and discourage RNNoise
  docs/dev/build-instructions/cmake_options.md
  installer/ClientInstaller.cs
  src/mumble/CMakeLists.txt
  src/tests/TestSettingsJSONSerialization/generate_test_case.py
Labels: client, audio

#6238 FIX(client): Fix using the keyboad to change local volume adjustment
  src/mumble/CMakeLists.txt
  src/mumble/ListenerVolumeSlider.cpp
  src/mumble/ListenerVolumeSlider.h
  src/mumble/UserLocalVolumeSlider.cpp
  src/mumble/UserLocalVolumeSlider.h
  src/mumble/VolumeSliderWidgetAction.cpp
  src/mumble/VolumeSliderWidgetAction.h
  src/mumble/widgets/EventFilters.cpp
  src/mumble/widgets/EventFilters.h
Labels: client, ui, backport-needed, bug, auto-backport-to-1.5.x
