Repository mumble-voip/mumble, pull requests merged in 2023-01, with the labels that each got.

#5926 FEAT(client): Always stop audio on/off cue when switching state
  src/mumble/API_v_1_x_x.cpp
  src/mumble/Audio.cpp
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioInput.cpp
  src/mumble/AudioInput.h
  src/mumble/AudioOutput.cpp
  src/mumble/AudioOutput.h
  src/mumble/AudioOutputBuffer.cpp
  src/mumble/AudioOutputBuffer.h
  src/mumble/AudioOutputSample.cpp
  src/mumble/AudioOutputSample.h
  src/mumble/AudioOutputSpeech.cpp
  src/mumble/AudioOutputSpeech.h
  src/mumble/AudioOutputToken.h
  src/mumble/AudioWizard.cpp
  src/mumble/AudioWizard.h
  src/mumble/CMakeLists.txt
  src/mumble/ClientUser.cpp
  src/mumble/Log.cpp
Labels: client, backport-needed, bug

#6007 Backport "Merge PR #6001: MAINT: Rewrite changelog script" to 1.5.x
  scripts/generateChangelog.py
  scripts/generate_changelog.py
Labels: backport

#6010 BUILD(cmake): Disable warnings as errors by default
  CMakeLists.txt
  docs/dev/build-instructions/cmake_options.md
Labels: build

#6011 CI(appveyor): Update to latest image version
  .appveyor.yml
Labels: backport-needed, auto-backport-to-1.5.x

#6012 Backport "Merge PR #6011: CI(appveyor): Update to latest image version" to 1.5.x
  .appveyor.yml
Labels: backport

#6002 BUILD(cmake): Always use DBus on Linux(-like) systems
  docs/dev/build-instructions/cmake_options.md
  src/CMakeLists.txt
  src/mumble/CMakeLists.txt
  src/mumble/Log_unix.cpp
  src/murmur/CMakeLists.txt
  src/murmur/DBus.h
  src/murmur/ServerDB.cpp
Labels: client, build, server

#6019 CI(appveyor): Fix vcvars path
  .appveyor.yml
Labels: backport-needed, ci, auto-backport-to-1.5.x

#6020 Backport "Merge PR #6019: CI(appveyor): Fix vcvars path" to 1.5.x
  .appveyor.yml
Labels: backport

#6016 MAINT: Added script for creating source archives
  scripts/create_source_archive.py
Labels: backport-needed, auto-backport-to-1.5.x

#6023 Backport "Merge PR #6016: MAINT: Added script for creating source archives" to 1.5.x
  scripts/create_source_archive.py
Labels: backport

#6022 CI(windows): Auto-determine path to vcvars script
  .appveyor.yml
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
  .ci/build_windows.bat
  .ci/install-environment_windows.ps1
Labels: backport-needed, ci, auto-backport-to-1.5.x

#6024 Backport "Merge PR #6022: CI(windows): Auto-determine path to vcvars script" to 1.5.x
  .appveyor.yml
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
  .ci/build_windows.bat
  .ci/install-environment_windows.ps1
Labels: backport

#6018 Backport "Merge PR #5926: FEAT(client): Always stop audio on/off cue when switching state" to 1.5.x
  src/mumble/API_v_1_x_x.cpp
  src/mumble/Audio.cpp
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioInput.cpp
  src/mumble/AudioInput.h
  src/mumble/AudioOutput.cpp
  src/mumble/AudioOutput.h
  src/mumble/AudioOutputBuffer.cpp
  src/mumble/AudioOutputBuffer.h
  src/mumble/AudioOutputSample.cpp
  src/mumble/AudioOutputSample.h
  src/mumble/AudioOutputSpeech.cpp
  src/mumble/AudioOutputSpeech.h
  src/mumble/AudioOutputToken.h
  src/mumble/AudioWizard.cpp
  src/mumble/AudioWizard.h
  src/mumble/CMakeLists.txt
  src/mumble/ClientUser.cpp
  src/mumble/Log.cpp
Labels: backport

#6025 CI(appveyor): Use release signing
  .appveyor.yml
Labels: backport-needed, ci, auto-backport-to-1.5.x

#6026 Backport "Merge PR #6025: CI(appveyor): Use release signing" to 1.5.x
  .appveyor.yml
Labels: backport

#6027 CI(github-actions): Avoid duplicate runs
  .github/workflows/build.yml
  .github/workflows/code-ql.yml
Labels: backport-needed, ci, auto-backport-to-1.5.x

#6028 Backport "Merge PR #6027: CI(github-actions): Avoid duplicate runs" to 1.5.x
  .github/workflows/build.yml
  .github/workflows/code-ql.yml
Labels: backport

#6032 BUILD(cmake): Fix server-only builds
  src/murmur/CMakeLists.txt
Labels: build

#6033 CI(github-actions): Ensure build number tagging
  .github/workflows/build.sh
  .github/workflows/build.yml
Labels: backport-needed, ci, auto-backport-to-1.5.x

#6034 Backport "Merge PR #6033: CI(github-actions): Ensure build number tagging" to 1.5.x
  .github/workflows/build.sh
  .github/workflows/build.yml
Labels: backport
