Repository mumble-voip/mumble, pull requests merged in 2023-04, with the labels that each got.

#6082 Backport "Merge PR #6081: BUILD(cmake): Install systemd related files on Linux only" to 1.5.x
  auxiliary_files/CMakeLists.txt
Labels: backport

#6044 FIX(server): Add ACL cache invalidation after user id is set
  src/murmur/Messages.cpp
Labels: server, backport-needed, bug, auto-backport-to-1.5.x

#6095 Backport "Merge PR #6044: FIX(server): Add ACL cache invalidation after user id is set" to 1.5.x
  src/murmur/Messages.cpp
Labels: backport

#6103 FIX(client): PipeWire crash
  src/mumble/PipeWire.cpp
Labels: client, audio, backport-needed, bug, auto-backport-to-1.5.x

#6104 Backport "Merge PR #6103: FIX(client): PipeWire crash" to 1.5.x
  src/mumble/PipeWire.cpp
Labels: backport

#6110 BUILD(cmake): Improve LTO handling
  CMakeLists.txt
  docs/dev/build-instructions/cmake_options.md
  src/CMakeLists.txt
  src/mumble/CMakeLists.txt
  src/murmur/CMakeLists.txt
Labels: build, backport-needed, auto-backport-to-1.5.x

#6111 Backport "Merge PR #6110: BUILD(cmake): Improve LTO handling" to 1.5.x
  CMakeLists.txt
  docs/dev/build-instructions/cmake_options.md
  src/CMakeLists.txt
  src/mumble/CMakeLists.txt
  src/murmur/CMakeLists.txt
Labels: backport

#6069 Translations update from Hosted Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#6118 Backport "Merge PR #6117: FIX(server): Actually use the settings provided pluginmessagelimit and -burst" to 1.5.x
  src/murmur/ServerUser.cpp
  src/murmur/ServerUser.h
Labels: backport
