Repository mumble-voip/mumble, pull requests merged in 2023-11, with the labels that each got.

#6252 Backport "Merge PR #6192: BUILD(cmake, overlay): Install 32-bit lib on FreeBSD" to 1.5.x
  overlay_gl/CMakeLists.txt
Labels: backport

#6251 Backport "Merge PR #6134: FEAT(client): Positional audio improvements" to 1.5.x
  src/mumble/AudioConfigDialog.cpp
  src/mumble/Settings.h
Labels: backport

#6246 REFAC(client): Get rid of launcher and DLL on Windows
  docs/dev/TheMumbleSourceCode.md
  installer/ClientInstaller.cs
  src/mumble/CMakeLists.txt
  src/mumble/Overlay_win.cpp
  src/mumble/main.cpp
  src/mumble/mumble_dll.rc.in
  src/mumble_exe/CMakeLists.txt
  src/mumble_exe/Overlay.cpp
  src/mumble_exe/mumble_exe.cpp
Labels: client, windows, backport-needed, auto-backport-to-1.5.x

#6256 FIX(client,theme): Use fixed dark font color for themeless notice labels
  src/mumble/Themes.cpp
Labels: theme, backport-needed, bug, qt, auto-backport-to-1.5.x

#6250 Backport "Merge PR #6234: FIX(client): Positional audio fixes" to 1.5.x
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioOutput.cpp
  src/mumble/ManualPlugin.cpp
Labels: backport

#6258 Backport "Merge PR #6246: REFAC(client): Get rid of launcher and DLL on Windows" to 1.5.x
  docs/dev/TheMumbleSourceCode.md
  installer/ClientInstaller.cs
  src/mumble/CMakeLists.txt
  src/mumble/Overlay_win.cpp
  src/mumble/main.cpp
  src/mumble/mumble_dll.rc.in
  src/mumble_exe/CMakeLists.txt
  src/mumble_exe/Overlay.cpp
  src/mumble_exe/mumble_exe.cpp
Labels: backport

#6259 Backport "Merge PR #6256: FIX(client,theme): Use fixed dark font color for themeless notice labels" to 1.5.x
  src/mumble/Themes.cpp
Labels: backport

#6219 FEAT(client): Add MP3 Recording
  src/mumble/CMakeLists.txt
  src/mumble/VoiceRecorder.cpp
  src/mumble/VoiceRecorder.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, recording, feature-request

#6265 TRANSLATION: Add missing word in audio wizard ui
  src/mumble/AudioWizard.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport-needed, translation, auto-backport-to-1.5.x

#6126 Translations update from Hosted Weblate
  src/mumble/mumble_br.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation
