Repository mumble-voip/mumble, pull requests merged in 2024-04, with the labels that each got.

#6370 FIX(client): Fix incorrect WASAPI sound device handling
  src/mumble/WASAPI.cpp
Labels: client, windows, audio, backport-needed, auto-backport-to-1.5.x

#6373 Backport "Merge PR #6371: FIX(client): Correctly subscribe to both sink and source events in PulseAudioSystem" to 1.5.x
  src/mumble/PulseAudio.cpp
Labels: backport

#6374 Backport "Merge pull request #6370 from Hartmnt/fix_wasapi_hopefully_haha" to 1.5.x
  src/mumble/WASAPI.cpp
Labels: backport

#6357 Translations update from Hosted Weblate
  src/mumble/mumble_ca.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_ro.ts
Labels: translation

#6372 FIX(server): Stale user pointers in whisper cache
  src/murmur/Messages.cpp
  src/murmur/Server.cpp
  src/murmur/Server.h
  src/murmur/ServerUser.h
Labels: server, backport-needed, bug, auto-backport-to-1.5.x

#6381 CI(github-actions): Upgrade to Node 20 actions
  .github/workflows/build.yml
Labels: ci

#6361 DOCS(ice): Add Channel.temporary read-only notice
  src/murmur/MumbleServer.ice
Labels: ice

#6384 MAINT(github): Drop forums web-link from issue templates
  .github/ISSUE_TEMPLATE/config.yml
Labels: github

#6386 DOCS(commit-guidelines): Fix headlines, Add general intro
  COMMIT_GUIDELINES.md
Labels: documentation

#6366 FEAT(client): disable pipewire input stream while muted
  src/mumble/AudioInput.cpp
  src/mumble/AudioInput.h
  src/mumble/Messages.cpp
  src/mumble/PipeWire.cpp
  src/mumble/PipeWire.h
Labels: client, audio

#6382 Backport "Merge PR #6372: FIX(server): Stale user pointers in whisper cache " to 1.5.x
  src/murmur/Messages.cpp
  src/murmur/Server.cpp
  src/murmur/Server.h
  src/murmur/ServerUser.h
Labels: backport

#6379 Translations update from Hosted Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation
