Repository mumble-voip/mumble, pull requests merged in 2024-11, with the labels that each got.

#6611 FIX(client): Fix AudioWizard echo cancellation checkbox
  src/mumble/AudioWizard.cpp
  src/mumble/AudioWizard.h
Labels: client, ui, bug, auto-backport-to-1.5.x

#6620 Backport "Merge PR #6611: FIX(client): Fix AudioWizard echo cancellation checkbox" to 1.5.x
  src/mumble/AudioWizard.cpp
  src/mumble/AudioWizard.h
Labels: backport

#6584 FIX(client): Specify version when loading/saving MainWindow state
  cmake/project-utils.cmake
  src/mumble/CMakeLists.txt
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/OverlayClient.cpp
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/SettingsMacros.h
Labels: client, bug, qt, auto-backport-to-1.5.x

#6640 FIX(cmake): Don't set WORKING_DIRECTORY for ExternalProject_Add()
  CMakeLists.txt
  helpers/g15helper/CMakeLists.txt
  overlay/CMakeLists.txt
  plugins/CMakeLists.txt
  src/mumble/CMakeLists.txt
Labels: windows, build, auto-backport-to-1.5.x

#6641 Backport "Merge PR #6640: FIX(cmake): Don't set WORKING_DIRECTORY for ExternalProject_Add()" to 1.5.x
  CMakeLists.txt
  helpers/g15helper/CMakeLists.txt
  overlay/CMakeLists.txt
  plugins/CMakeLists.txt
  src/mumble/CMakeLists.txt
Labels: backport
