Repository mumble-voip/mumble, pull requests merged in 2024-06, with the labels that each got.

#6426 FIX(client): Crash when loading settings
  src/mumble/ConfigDialog.cpp
Labels: client, backport-needed, bug, qt, auto-backport-to-1.5.x

#6444 FIX(client): Capture "this" explicitly in lambdas
  src/mumble/GlobalShortcut.cpp
  src/mumble/ListenerVolumeSlider.cpp
  src/mumble/VolumeSliderWidgetAction.cpp
Labels: client

#6446 Backport "Merge PR #6426: FIX(client): Crash when loading settings" to 1.5.x
  src/mumble/ConfigDialog.cpp
Labels: backport

#6440 FIX(client): Correctly remember muted state across restarts
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/Settings.h
  src/mumble/SettingsKeys.h
  src/mumble/SettingsMacros.h
Labels: client, backport-needed, bug, auto-backport-to-1.5.x

#6448 Backport "Merge PR #6440: FIX(client): Correctly remember muted state across restarts" to 1.5.x
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/Settings.h
  src/mumble/SettingsKeys.h
  src/mumble/SettingsMacros.h
Labels: backport

#6447 Backport "Merge PR #6444: FIX(client): Capture "this" explicitly in lambdas" to 1.5.x
  src/mumble/GlobalShortcut.cpp
  src/mumble/ListenerVolumeSlider.cpp
  src/mumble/VolumeSliderWidgetAction.cpp
Labels: backport

#6443 FIX(client): Improve handling of the GlobalShortcutButtons dialog
  src/mumble/GlobalShortcutButtons.cpp
Labels: client, ui, backport-needed, external-bug, bug, auto-backport-to-1.5.x

#6442 FIX(client): Remove placeholder wrapping in ChatBar
  src/mumble/CustomElements.cpp
  src/mumble/CustomElements.h
  src/mumble/QtWidgetUtils.cpp
Labels: client, ui, backport-needed, bug, auto-backport-to-1.5.x

#6449 Backport "Merge PR #6443: FIX(client): Improve handling of the GlobalShortcutButtons dialog" to 1.5.x
  src/mumble/GlobalShortcutButtons.cpp
Labels: backport

#6450 Backport "Merge PR #6442: FIX(client): Remove placeholder wrapping in ChatBar" to 1.5.x
  src/mumble/CustomElements.cpp
  src/mumble/CustomElements.h
  src/mumble/QtWidgetUtils.cpp
Labels: backport

#6422 Translations update from Hosted Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_pt_BR.ts
Labels: translation

#6441 FIX(ui): Remove mention of variable bitrate from UI
  src/mumble/AudioInput.ui
  src/mumble/AudioStats.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, ui, bug

#6454 FIX(server): Allow to move temporary channels provided sufficient per…
  src/murmur/Messages.cpp
Labels: server, acl, backport-needed, bug, auto-backport-to-1.5.x

#6456 Backport "Merge PR #6454: FIX(server): Allow to move temporary channels provided sufficient per…" to 1.5.x
  src/murmur/Messages.cpp
Labels: backport

#6457 Fix the QComboBoxes in ACLEditor
  src/mumble/ACLEditor.cpp
  src/mumble/ACLEditor.h
  src/mumble/widgets/EventFilters.cpp
  src/mumble/widgets/EventFilters.h
Labels: client, ui, backport-needed, bug, accessibility, auto-backport-to-1.5.x

#6474 BUILD: Use correct type for num locks
  src/SSLLocks.cpp
Labels: build, backport-needed, auto-backport-to-1.5.x

#6475 Backport "Merge PR #6474: BUILD: Use correct type for num locks" to 1.5.x
  src/SSLLocks.cpp
Labels: backport

#6452 Translations update from Hosted Weblate
  src/mumble/mumble_es.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_TW.ts
Labels: translation

#6478 FIX(client): Update tab order in AudioInput.ui
  src/mumble/AudioInput.ui
Labels: client, backport-needed, bug, qt, auto-backport-to-1.5.x

#6481 Backport "Merge PR #6478: FIX(client): Update tab order in AudioInput.ui" to 1.5.x
  src/mumble/AudioInput.ui
Labels: backport

#6458 FEAT(client): Clear local mutes on Mumble restart
  src/mumble/Database.cpp
  src/mumble/Database.h
  src/mumble/main.cpp
Labels: client, feature-request
