Repository mumble-voip/mumble, pull requests merged in 2024-02, with the labels that each got.

#6329 FIX(client): Fix the size_t type for QT invoke functions in API.
  src/mumble/API.h
  src/mumble/API_v_1_x_x.cpp
Labels: client, bug

#6339 FIX(server): Allow unregistered users to transmit access tokens
  src/murmur/Messages.cpp
Labels: server, bug

#6270 Translations update from Hosted Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#6309 FIX(client, ui): Fix log scroll position after loading resources
  src/mumble/CustomElements.cpp
  src/mumble/CustomElements.h
  src/mumble/Log.cpp
  src/mumble/Log.h
Labels: client, ui, bug

#6348 FIX(ui): Preserve other check-box states if All messages was checked
  src/mumble/Log.cpp
Labels: client, ui, bug

#6350 FIX(client): Use IPv4 HostAddress representation where applicable
  src/HostAddress.cpp
Labels: client, bug
