Repository mumble-voip/mumble, pull requests merged in 2024-10, with the labels that each got.

#6582 MAINT(readme): Update Docker usage instructions
  README.md
Labels: auto-backport-to-1.5.x

#6590 CI(backport): Refine label checker action
  .github/workflows/backport.yml
Labels: ci

#6592 CI(backoprt): Fix workflow file
  .github/workflows/backport.yml
Labels: ci

#6593 CI(backport): Fix label checker version
  .github/workflows/backport.yml
Labels: ci

#6588 DOCS(vcpkg): Refer to our own vcpkg fork
  docs/dev/build-instructions/build_static.md
  helpers/vcpkg/ports/zeroc-ice-mumble/CONTROL
  helpers/vcpkg/ports/zeroc-ice-mumble/portfile.cmake
  scripts/vcpkg/get_mumble_dependencies.ps1
  scripts/vcpkg/get_mumble_dependencies.sh
Labels: documentation, auto-backport-to-1.5.x

#6580 BREAK(server): Remove DBus support
  3rdPartyLicenses/dbus_license.txt
  auxiliary_files/mumble-server.ini
  auxiliary_files/run_scripts/mumble-server-user-wrapper.in
  scripts/generate_license_header.py
  src/murmur/CMakeLists.txt
  src/murmur/DBus.cpp
  src/murmur/DBus.h
  src/murmur/Messages.cpp
  src/murmur/Meta.cpp
  src/murmur/Meta.h
  src/murmur/Server.h
  src/murmur/UnixMurmur.cpp
  src/murmur/main.cpp
Labels: server

#6564 Translations update from Hosted Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#6578 FIX(client): Limit size of the chat bar
  src/mumble/CustomElements.cpp
Labels: client, ui, bug, auto-backport-to-1.5.x

#6326 FEAT(client): Toggle positional audio shortcut #6133
  src/mumble/GlobalShortcutTypes.h
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, feature-request

#6595 Backport "Merge PR #6578: FIX(client): Limit size of the chat bar" to 1.5.x
  src/mumble/CustomElements.cpp
Labels: backport

#6598 FIX(plugins): Load correct pages for modules
  plugins/HostWindows.cpp
Labels: client, positional audio, bug, auto-backport-to-1.5.x

#6600 Backport "Merge PR #6598: FIX(plugins): Load correct pages for modules" to 1.5.x
  plugins/HostWindows.cpp
Labels: backport

#6615 FIX(client): Use correct off audio cue
  src/mumble/Settings.h
Labels: client, bug, auto-backport-to-1.5.x

#6616 Backport "Merge PR #6615: FIX(client): Use correct off audio cue" to 1.5.x
  src/mumble/Settings.h
Labels: backport
