Repository mumble-voip/mumble, pull requests merged in 2024-07, with the labels that each got.

#6484 MAINT(ci): Upgrade to macOS 12 on Azure Pipelines
  .ci/azure-pipelines/main.yml
Labels: ci

#6486 FIX(client): Do not spam log when adjusting volume of clients without certificate
  src/mumble/UserLocalVolumeSlider.cpp
  src/mumble/UserLocalVolumeSlider.h
Labels: client, ui, backport-needed, bug, auto-backport-to-1.5.x

#6494 MAINT(ci): Various maintenance work related to CI configs
  .ci/azure-pipelines/install-environment_linux.bash
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
  .github/workflows/backport.yml
  .github/workflows/build.yml
  .github/workflows/code-ql.yml
  .github/workflows/pr-checks.yml
  .github/workflows/release_dispatch.yml
  .github/workflows/stale_issues.yml
Labels: ci

#6495 Backport "MAINT(ci): Various maintenance work related to CI configs" to 1.5.x
  .ci/azure-pipelines/install-environment_linux.bash
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
  .github/workflows/backport.yml
  .github/workflows/build.yml
  .github/workflows/code-ql.yml
  .github/workflows/pr-checks.yml
  .github/workflows/release_dispatch.yml
  .github/workflows/stale_issues.yml
Labels: backport

#6497 Backport "MAINT: Only run backport action when PR is merged" to 1.5.x
  .github/workflows/backport.yml
Labels: backport

#6499 FIX(client, plugins): Wrong sample count in plugin callback
  src/mumble/AudioInput.cpp
Labels: client, bug, auto-backport-to-1.5.x

#6500 Backport "Merge PR #6498: MAINT: Update backport config" to 1.5.x
  .backportrc.json
Labels: backport

#6502 MAINT(ci): Don't run backport action on backport PRs
  .github/workflows/backport.yml
Labels: ci, auto-backport-to-1.5.x

#6503 Backport "Merge PR #6502: MAINT(ci): Don't run backport action on backport PRs" to 1.5.x
  .github/workflows/backport.yml
Labels: backport

#6485 Update winget-releaser to latest
  .github/workflows/winget.yml
Labels: ci

#6488 Backport "Merge PR #6486: FIX(client): Do not spam log when adjusting volume of clients without certificate" to 1.5.x
  src/mumble/UserLocalVolumeSlider.cpp
  src/mumble/UserLocalVolumeSlider.h
Labels: backport
