Repository mumble-voip/mumble, pull requests merged in 2024-09, with the labels that each got.

#6535 Backport "Merge PR #6510: FIX(client): Fix crash on mono pos. audio warning from audio thread" to 1.5.x
  src/mumble/AudioOutput.cpp
  src/mumble/Log.cpp
Labels: backport

#6538 Backport "Merge PR #6536: BUILD: Fix compiler warnings on 32bit architectures" to 1.5.x
  src/MumbleProtocol.cpp
  src/mumble/Audio.cpp
  src/mumble/AudioOutput.cpp
  src/murmur/Server.cpp
Labels: backport

#6553 FIX(client, server): Remove redundant OpenSSL locking callback check
  src/SSL.cpp
Labels: client, server, bug, auto-backport-to-1.5.x

#6555 Backport "Merge PR #6553: FIX(client, server): Remove redundant OpenSSL locking callback check" to 1.5.x
  src/SSL.cpp
Labels: backport

#6559 FIX(server): Change server thread name to "mumble-server" instead of "Main"
  src/murmur/Server.cpp
Labels: server, bug, auto-backport-to-1.5.x

#6561 Backport "Merge PR #6559: FIX(server): Change server thread name to "mumble-server" instead of "Main"" to 1.5.x
  src/murmur/Server.cpp
Labels: backport

#6480 Translations update from Hosted Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: translation

#6562 Remove mentions of the Mumble wiki
  README.md
  auxiliary_files/config_files/info.mumble.Mumble.appdata.xml.in
  docs/dev/ExtendingTheIceInterface.md
  docs/dev/TheMumbleSourceCode.md
  src/mumble/NetworkConfig.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, ui, documentation, auto-backport-to-1.5.x

#6563 Backport "Merge PR #6562: Remove mentions of the Mumble wiki" to 1.5.x
  README.md
  auxiliary_files/config_files/info.mumble.Mumble.appdata.xml.in
  docs/dev/ExtendingTheIceInterface.md
  docs/dev/TheMumbleSourceCode.md
  src/mumble/NetworkConfig.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport

#6565 FIX(client): Replace dead URL in Certificate Wizard
  src/mumble/Cert.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, ui, bug, auto-backport-to-1.5.x

#6566 Backport "Merge PR #6565: FIX(client): Replace dead URL in Certificate Wizard" to 1.5.x
  src/mumble/Cert.ui
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: backport

#6570 FIX(client): Prevent sending plain text on fast CTRL+V + ENTER
  src/mumble/CustomElements.cpp
  src/mumble/CustomElements.h
  src/mumble/GlobalShortcut_unix.h
Labels: client, ui, bug, auto-backport-to-1.5.x

#6573 Backport "Merge PR #6570: FIX(client): Prevent sending plain text on fast CTRL+V + ENTER" to 1.5.x
  src/mumble/CustomElements.cpp
  src/mumble/CustomElements.h
  src/mumble/GlobalShortcut_unix.h
Labels: backport

#6574 FIX(client): Save local volume adjustment when clicking slider bar
  src/mumble/VolumeSliderWidgetAction.cpp
Labels: client, ui, bug, auto-backport-to-1.5.x

#6575 Backport "Merge PR #6574: FIX(client): Save local volume adjustment when clicking slider bar" to 1.5.x
  src/mumble/VolumeSliderWidgetAction.cpp
Labels: backport

#6571 FIX(client): Registered AudioOutputBuffer as qRegisterMetaType
  src/mumble/AudioOutput.cpp
Labels: client, audio, bug

#6572 DOCS: Update dependencies for Qt6
  docs/dev/build-instructions/README.md
  docs/dev/build-instructions/build_linux.md
Labels: documentation

#6581 CI(backport): Prevent CI failure for non-backported PRs
  .github/workflows/backport.yml
Labels: ci
