Repository mumble-voip/mumble, pull requests merged in 2024-01, with the labels that each got.

#6295 BUILD: Auto-determine Windows xcompile triplet
  overlay/CMakeLists.txt
Labels: build

#6158 FEAT(client): Add setting to always show user in Talking UI
  src/mumble/LookConfig.cpp
  src/mumble/LookConfig.h
  src/mumble/LookConfig.ui
  src/mumble/Settings.h
  src/mumble/SettingsKeys.h
  src/mumble/SettingsMacros.h
  src/mumble/TalkingUI.cpp
  src/mumble/TalkingUIEntry.cpp
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, ui, feature-request

#6100 BUILD(cmake): Improve install handling
  CMakeLists.txt
  auxiliary_files/CMakeLists.txt
  auxiliary_files/config_files/mumble-server.conf
  auxiliary_files/config_files/mumble-server.tmpfiles.in
  auxiliary_files/run_scripts/mumble-server-user-wrapper.in
  cmake/install-paths.cmake
  cmake/pkg-utils.cmake
  docs/dev/build-instructions/cmake_options.md
  scripts/generate_cmake_options_docs.py
Labels: build, release-management

#6298 FIX(client): Invalid code-block regex
  src/mumble/Markdown.cpp
Labels: client, bug

#6155 FEAT(client): Add popup when mute cue is activated for the first time
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioInput.cpp
  src/mumble/AudioInput.h
  src/mumble/Global.cpp
  src/mumble/Global.h
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/Settings.h
  src/mumble/SettingsKeys.h
  src/mumble/SettingsMacros.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, ui, feature-request

#6315 CI(freebsd): Build with C++17
  .cirrus.yml
  CMakeLists.txt
Labels: ci

#6307 FIX(client): Crash when opening connect dialog
  src/mumble/ConnectDialog.cpp
Labels: client, bug

#6314 BUILD: Detect arm64 / aarch64 architecture
  cmake/TargetArch.cmake
Labels: client, build

#6316 FIX(client): Fix PulseAudio regression by nulling buffer
  src/mumble/PulseAudio.cpp
Labels: client, linux, audio, bug

#6321 FIX(shared): Crash in HostAddress::toIPv4()
  src/HostAddress.cpp
Labels: client, server
