Repository mumble-voip/mumble, pull requests merged in 2024-12, with the labels that each got.

#6637 DOCS(server): Add Documentation key to mumble-server unit
  auxiliary_files/config_files/mumble-server.service.in
Labels: documentation, auto-backport-to-1.5.x

#6635 FIX(client): Fix Windows Unicode paths when using raw file streams
  src/QtUtils.cpp
  src/QtUtils.h
  src/mumble/PluginInstaller.cpp
  src/mumble/Settings.cpp
Labels: client, windows, bug

#6624 Translations update from Hosted Weblate
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#6648 Backport "FIX(client): Fix Windows Unicode paths when using raw file streams #6635" to 1.5.x
  src/QtUtils.cpp
  src/QtUtils.h
  src/mumble/PluginInstaller.cpp
  src/mumble/Settings.cpp
Labels: client, windows, bug, backport

#6649 CI(appveyor): Workaround for FXC failing to run with error C0000139
  .appveyor.yml
Labels: ci

#6646 DOCS: Update Debian Build-Dependencies
  docs/dev/build-instructions/build_linux.md
Labels: documentation

#6625 Backport "Merge PR #6584: FIX(client): Specify version when loading/saving MainWindow state" to 1.5.x
  cmake/project-utils.cmake
  src/mumble/CMakeLists.txt
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/OverlayClient.cpp
  src/mumble/Settings.cpp
  src/mumble/Settings.h
  src/mumble/SettingsMacros.h
Labels: backport

#6672 DOCS: Mention differences in documentation across branches
  README.md
  docs/dev/build-instructions/README.md
Labels: documentation
