Repository mumble-voip/mumble, pull requests merged in 2025-06, with the labels that each got.

#6844 Backport "Merge PR #6841: FIX(client): Add more key events to local volume adjustment slider" to 1.5.x
  src/mumble/VolumeSliderWidgetAction.cpp
Labels: backport

#6789 FEAT(installer): Bundle C++ redistributables
  .ci/azure-pipelines/release_windows.bat
  CMakeLists.txt
  installer/ClientInstaller.cs
  installer/MumbleInstall.cs
  installer/ServerInstaller.cs
  installer/Theme.xml
  src/mumble/CMakeLists.txt
  src/murmur/CMakeLists.txt
Labels: windows, installer, auto-backport-to-1.5.x

#6853 Backport "Merge PR #6789: FEAT(installer): Bundle C++ redistributables" to 1.5.x
  .ci/azure-pipelines/release_windows.bat
  CMakeLists.txt
  installer/ClientInstaller.cs
  installer/MumbleInstall.cs
  installer/ServerInstaller.cs
  installer/Theme.xml
  src/mumble/CMakeLists.txt
  src/murmur/CMakeLists.txt
Labels: backport

#6804 FEAT(client): Listener attenuation
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioConfigDialog.h
  src/mumble/AudioOutput.cpp
  src/mumble/AudioOutput.ui
  src/mumble/GlobalShortcutTypes.h
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/Settings.h
  src/mumble/SettingsKeys.h
  src/mumble/SettingsMacros.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
Labels: client, feature-request

#6855 Backport "Merge PR #6852: FIX(client): Crash in PipeWire when the main thread is null" to 1.5.x
  src/mumble/PipeWire.cpp
Labels: backport

#6859 Fix Write and Traverse ACL permission regressions
  src/ACL.cpp
Labels: server, bug, auto-backport-to-1.5.x

#6860 Backport "Merge PR #6859: Fix Write and Traverse ACL permission regressions" to 1.5.x
  src/ACL.cpp
Labels: backport
