Repository mumble-voip/mumble, pull requests merged in 2025-02, with the labels that each got.

#6687 Translations update from Hosted Weblate
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#6723 CI(cirrus): Update to FreeBSD 14.2
  .cirrus.yml
Labels: ci, auto-backport-to-1.5.x

#6724 Backport "Merge PR #6723: CI(cirrus): Update to FreeBSD 14.2" to 1.5.x
  .cirrus.yml
Labels: backport

#6728 FIX(Client): bug with talking UI options
  src/mumble/LookConfig.cpp
Labels: client, ui, bug, auto-backport-to-1.5.x

#6732 Backport "Merge PR #6728: FIX(Client): bug with talking UI options" to 1.5.x
  src/mumble/LookConfig.cpp
Labels: backport
