Repository mumble-voip/mumble, pull requests merged in 2025-01, with the labels that each got.

#6512 FIX(server, client): Fix ACL write and traverse permissions
  src/ACL.cpp
  src/mumble/ACLEditor.cpp
  src/mumble/MainWindow.cpp
  src/murmur/Messages.cpp
Labels: client, server, acl, ui, bug, auto-backport-to-1.5.x

#6623 DOCS(protocol): Integrate network protocol documentation
  docs/dev/Network-Protocol.md
  docs/dev/network-protocol/README.rst
  docs/dev/network-protocol/establishing_connection.rst
  docs/dev/network-protocol/overview.rst
  docs/dev/network-protocol/protocol_stack_tcp.rst
  docs/dev/network-protocol/resources/mumble_connection_setup.odg
  docs/dev/network-protocol/resources/mumble_connection_setup.pdf
  docs/dev/network-protocol/resources/mumble_connection_setup.png
  docs/dev/network-protocol/resources/mumble_crypt_types.odg
  docs/dev/network-protocol/resources/mumble_crypt_types.pdf
  docs/dev/network-protocol/resources/mumble_crypt_types.png
  docs/dev/network-protocol/resources/mumble_packet.odg
  docs/dev/network-protocol/resources/mumble_packet.pdf
  docs/dev/network-protocol/resources/mumble_packet.png
  docs/dev/network-protocol/resources/mumble_protocol_stack.odg
  docs/dev/network-protocol/resources/mumble_protocol_stack.pdf
  docs/dev/network-protocol/resources/mumble_protocol_stack.png
  docs/dev/network-protocol/resources/mumble_system_overview.odg
  docs/dev/network-protocol/resources/mumble_system_overview.pdf
  docs/dev/network-protocol/resources/mumble_system_overview.png
  docs/dev/network-protocol/voice_data.rst
Labels: documentation

#6684 REFAC: Remove unused CryptState.h
  src/CryptState.h
Labels: auto-backport-to-1.5.x

#6685 Backport "Merge PR #6684: REFAC: Remove unused CryptState.h" to 1.5.
  src/CryptState.h
Labels: backport

#6655 Translations update from Hosted Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_uk.ts
Labels: translation

#6691 FIX(server): Respect Qt's desired initialization order
  scripts/generateIceWrapper.py
  src/PacketDataStream.cpp
  src/backup
  src/murmur/Cert.cpp
  src/murmur/Messages.cpp
  src/murmur/Meta.cpp
  src/murmur/Meta.h
  src/murmur/MumbleServerIce.cpp
  src/murmur/Register.cpp
  src/murmur/Server.cpp
  src/murmur/ServerDB.cpp
  src/murmur/UnixMurmur.cpp
  src/murmur/main.cpp
Labels: server, bug

#6602 FIX(plugins): Unset active positional plugin on unloading it
  src/mumble/PluginManager.cpp
  src/mumble/PluginManager.h
Labels: client, positional audio, bug, auto-backport-to-1.5.x

#6692 FIX(installer): Drop (outdated) copyright year from license
  installer/Mumble.rtf
Labels: installer

#6694 REFAC(server): Add explicit casts to avoid conversion warnings
  src/murmur/ServerUser.cpp
  src/murmur/ServerUser.h
Labels: server

#6695 Backport "Merge PR #6602: FIX(plugins): Unset active positional plugin on unloading it" to 1.5.x
  src/mumble/PluginManager.cpp
  src/mumble/PluginManager.h
Labels: backport

#6604 FIX(client): Fix memory leaks due to BIO_NOCLOSE flag
  src/mumble/Cert.cpp
  src/murmur/Cert.cpp
Labels: client, bug, auto-backport-to-1.5.x

#6698 Backport "Merge PR #6604: FIX(client): Fix memory leaks due to BIO_NOCLOSE flag"
  src/mumble/Cert.cpp
  src/murmur/Cert.cpp
Labels: backport

#6699 Backport "Merge PR #6694: REFAC(server): Add explicit casts to avoid conversion warnings" to 1.5.x
  src/murmur/ServerUser.cpp
  src/murmur/ServerUser.h
Labels: backport

#6700 CHANGE(server): Extended user stats now requires Ban ACL
  src/murmur/Messages.cpp
Labels: server, auto-backport-to-1.5.x

#6703 MAINT(ci): Update to macOS 14 on Azure Pipelines
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
Labels: ci, auto-backport-to-1.5.x

#6705 Backport "Merge PR #6703: MAINT(ci): Update to macOS 14 on Azure Pipelines" to 1.5.x
  .ci/azure-pipelines/main-pr.yml
  .ci/azure-pipelines/main.yml
Labels: backport

#6702 FIX(client): Infinite loop and log spam on ALSA input device disconnection
  src/mumble/ALSAAudio.cpp
Labels: client, audio, auto-backport-to-1.5.x

#6706 Backport "Merge PR #6702: FIX(client): Infinite loop and log spam on ALSA input device disconnection" to 1.5.x
  src/mumble/ALSAAudio.cpp
Labels: backport

#6701 Backport "Merge PR #6700: CHANGE(server): Extended user stats now requires Ban ACL" to 1.5.x
  src/murmur/Messages.cpp
Labels: backport

#6511 REFAC(client): Introduce and use AudioPreprocessor
  src/mumble/AudioConfigDialog.cpp
  src/mumble/AudioInput.cpp
  src/mumble/AudioInput.h
  src/mumble/AudioPreprocessor.cpp
  src/mumble/AudioPreprocessor.h
  src/mumble/AudioStats.cpp
  src/mumble/CMakeLists.txt
Labels: client

#6714 DOCS(dev): Clean up network protocol docs
  docs/dev/network-protocol/establishing_connection.rst
  docs/dev/network-protocol/voice_data.rst
Labels: documentation
