Repository mumble-voip/mumble, pull requests merged in 2025-05, with the labels that each got.

#6674 FEAT(client): Move back to previous channel(s)
  scripts/updatetranslations.py
  src/mumble/GlobalShortcutTypes.h
  src/mumble/MainWindow.cpp
  src/mumble/MainWindow.h
  src/mumble/MainWindow.ui
  src/mumble/UserModel.cpp
  src/mumble/UserModel.h
  src/mumble/mumble_ar.ts
  src/mumble/mumble_bg.ts
  src/mumble/mumble_br.ts
  src/mumble/mumble_ca.ts
  src/mumble/mumble_cs.ts
  src/mumble/mumble_cy.ts
  src/mumble/mumble_da.ts
  src/mumble/mumble_de.ts
  src/mumble/mumble_el.ts
  src/mumble/mumble_en.ts
  src/mumble/mumble_en_GB.ts
  src/mumble/mumble_eo.ts
  src/mumble/mumble_es.ts
  src/mumble/mumble_et.ts
  src/mumble/mumble_eu.ts
  src/mumble/mumble_fa_IR.ts
  src/mumble/mumble_fi.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_gl.ts
  src/mumble/mumble_he.ts
  src/mumble/mumble_hi.ts
  src/mumble/mumble_hu.ts
  src/mumble/mumble_it.ts
  src/mumble/mumble_ja.ts
  src/mumble/mumble_ko.ts
  src/mumble/mumble_lt.ts
  src/mumble/mumble_nl.ts
  src/mumble/mumble_no.ts
  src/mumble/mumble_oc.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_pt_BR.ts
  src/mumble/mumble_pt_PT.ts
  src/mumble/mumble_ro.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_si.ts
  src/mumble/mumble_sk.ts
  src/mumble/mumble_sq.ts
  src/mumble/mumble_sv.ts
  src/mumble/mumble_te.ts
  src/mumble/mumble_th.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
  src/mumble/mumble_zh_HK.ts
  src/mumble/mumble_zh_TW.ts
  themes/Default/arrow_left.svg
  themes/DefaultTheme.qrc
Labels: client, feature-request

#6673 FEAT(server): Allow running while DB is in read-only mode
  docs/dev/ExtendingTheIceInterface.md
  src/Mumble.proto
  src/MumbleProtocol.cpp
  src/MumbleProtocol.h
  src/murmur/DBState.h
  src/murmur/Meta.h
  src/murmur/MumbleServer.ice
  src/murmur/MumbleServerI.h
  src/murmur/MumbleServerIce.cpp
  src/murmur/Server.cpp
Labels: server, feature-request

#6813 FIX(client): Fix regression of QComboBox activation in Qt6
  src/mumble/ACLEditor.cpp
  src/mumble/ACLEditor.h
Labels: client, ui, bug

#6765 Translations update from Hosted Weblate
  src/mumble/mumble_de.ts
  src/mumble/mumble_fr.ts
  src/mumble/mumble_pl.ts
  src/mumble/mumble_ru.ts
  src/mumble/mumble_tr.ts
  src/mumble/mumble_uk.ts
  src/mumble/mumble_zh_CN.ts
Labels: translation

#6829 Backport "Merge PR #6825: CHANGE(client): Changed client-side max image width and height" to 1.5.x
  src/mumble/Log.cpp
Labels: backport

#6832 FIX(client): Shortcut data not being saved
  src/mumble/Settings.h
Labels: client, backport-needed, auto-backport-to-1.5.x

#6840 Backport "Merge PR #6832: FIX(client): Shortcut data not being saved" to 1.5.x
  src/mumble/Settings.h
Labels: backport

#6824 Documentation Updates
  auxiliary_files/mumble-server.ini
  docs/dev/build-instructions/README.md
  docs/dev/build-instructions/build_macos.md
  scripts/updatetranslations.py
Labels: documentation
